from pathlib import Path

proof = Path("product/tradercockpit/research_proof.py")
text = proof.read_text(encoding="utf-8")
old_import = '''from tradercockpit.research_robustness import (\n    ROBUSTNESS_METHOD_HIGHER_PRECISION,\n    ROBUSTNESS_OPERATION,\n    ROBUSTNESS_OUTCOME_UNREAD,\n    ResearchRobustnessError,\n    read_native_robustness_result,\n)\n'''
new_import = '''from tradercockpit.research_robustness import (\n    ROBUSTNESS_ATTEMPT_SCHEMA,\n    ROBUSTNESS_METHOD_HIGHER_PRECISION,\n    ROBUSTNESS_OPERATION,\n    ROBUSTNESS_OUTCOME_UNREAD,\n    ROBUSTNESS_RECORD_SCHEMA,\n    ResearchRobustnessError,\n    read_native_robustness_result,\n)\n'''
if old_import not in text:
    raise SystemExit("robustness import anchor mismatch")
text = text.replace(old_import, new_import, 1)
old_catalog = '''        try:\n            raw = json.loads(store.read_revision_content(revision))\n        except (UnicodeDecodeError, json.JSONDecodeError):\n            # Robustness also uses ResearchKind.PROOF. Its strict validators own its\n            # schemas; a malformed foreign Proof must not become user Proof authority.\n            continue\n        if isinstance(raw, dict) and raw.get("schema") == RESEARCH_PROOF_CONTENT_SCHEMA:\n            entities.append(entity)\n'''
new_catalog = '''        try:\n            raw = json.loads(store.read_revision_content(revision))\n        except (UnicodeDecodeError, json.JSONDecodeError) as exc:\n            raise ResearchProofError(\n                "research_proof_catalog_corrupt",\n                "current Proof content is not valid JSON",\n            ) from exc\n        if not isinstance(raw, dict):\n            raise ResearchProofError("research_proof_catalog_corrupt", "current Proof content is not an object")\n        schema = raw.get("schema")\n        if schema == RESEARCH_PROOF_CONTENT_SCHEMA:\n            entities.append(entity)\n            continue\n        if schema in {ROBUSTNESS_RECORD_SCHEMA, ROBUSTNESS_ATTEMPT_SCHEMA}:\n            # Native Robustness shares ResearchKind.PROOF custody. Its strict\n            # catalog owns only these registered sibling schemas.\n            continue\n        raise ResearchProofError(\n            "research_proof_catalog_corrupt",\n            "current Proof schema is not a registered Research Proof schema",\n        )\n'''
if old_catalog not in text:
    raise SystemExit("user Proof catalog anchor mismatch")
text = text.replace(old_catalog, new_catalog, 1)
old_read = '''    if not isinstance(payload, dict) or payload.get("schema") != RESEARCH_PROOF_CONTENT_SCHEMA:\n        raise ResearchProofError("research_proof_not_user_proof", "Proof entity belongs to another registered Proof schema")\n    return _record(store, entity, revision)\n'''
new_read = '''    if not isinstance(payload, dict):\n        raise ResearchProofError("research_proof_content_corrupt", "Proof content is not an object")\n    schema = payload.get("schema")\n    if schema in {ROBUSTNESS_RECORD_SCHEMA, ROBUSTNESS_ATTEMPT_SCHEMA}:\n        raise ResearchProofError("research_proof_not_user_proof", "Proof entity belongs to a registered native Robustness schema")\n    if schema != RESEARCH_PROOF_CONTENT_SCHEMA:\n        raise ResearchProofError("research_proof_content_corrupt", "Proof entity uses an unregistered Proof schema")\n    return _record(store, entity, revision)\n'''
if old_read not in text:
    raise SystemExit("targeted user Proof read anchor mismatch")
text = text.replace(old_read, new_read, 1)
proof.write_text(text, encoding="utf-8")

tests = Path("tests/product/test_research_proof.py")
test_text = tests.read_text(encoding="utf-8")
anchor = '''    def test_duplicate_exact_proof_is_reused(self):\n'''
regression = '''    def test_catalog_fails_closed_on_malformed_or_unregistered_proof_schema(self):\n        for content in (b"not-json", b'{"schema":"tc.other-proof.v1"}'):\n            with self.subTest(content=content):\n                with TemporaryDirectory() as tmp:\n                    store = FileResearchCustodyStore(Path(tmp) / "data")\n                    foreign = store.create_entity(ResearchKind.PROOF)\n                    foreign_revision = store.create_revision(foreign, content)\n                    store.compare_and_set_current(\n                        foreign,\n                        expected_revision=None,\n                        target_revision=foreign_revision.revision,\n                    )\n                    with self.assertRaises(ResearchProofError) as caught:\n                        list_current_research_proofs(store)\n                    self.assertEqual(caught.exception.code, "research_proof_catalog_corrupt")\n\n    def test_targeted_read_distinguishes_registered_robustness_from_unknown_proof_schema(self):\n        robustness = self.store.create_entity(ResearchKind.PROOF)\n        robustness_revision = self.store.create_revision(\n            robustness,\n            b'{"schema":"tc.research-native-robustness-attempt.v1","state":"failed"}',\n        )\n        self.store.compare_and_set_current(robustness, expected_revision=None, target_revision=robustness_revision.revision)\n        with self.assertRaises(ResearchProofError) as sibling:\n            read_current_research_proof(self.store, robustness)\n        self.assertEqual(sibling.exception.code, "research_proof_not_user_proof")\n\n        unknown = self.store.create_entity(ResearchKind.PROOF)\n        unknown_revision = self.store.create_revision(unknown, b'{"schema":"tc.other-proof.v1"}')\n        self.store.compare_and_set_current(unknown, expected_revision=None, target_revision=unknown_revision.revision)\n        with self.assertRaises(ResearchProofError) as corrupt:\n            read_current_research_proof(self.store, unknown)\n        self.assertEqual(corrupt.exception.code, "research_proof_content_corrupt")\n\n''' + anchor
if anchor not in test_text:
    raise SystemExit("user Proof fail-closed regression anchor mismatch")
test_text = test_text.replace(anchor, regression, 1)
tests.write_text(test_text, encoding="utf-8")
