        (sqGetIndicatorValue(${getIndyShortName(getIndicatorId(block))}, <@printShift block "1" />) < 0)
        && (sqGetIndicatorValue(${getIndyShortName(getIndicatorId(block))}, <@printShift block "2" />) < 0)
        && (sqGetIndicatorValue(${getIndyShortName(getIndicatorId(block))}, <@printShift block "3" />) < 0)
        && (sqGetIndicatorValue(${getIndyShortName(getIndicatorId(block))}, <@printShift block "4" />) < 0)
        && (sqGetIndicatorValue(${getIndyShortName(getIndicatorId(block))}, <@printShift block "5" />) < 0)
        && (sqGetIndicatorValue(${getIndyShortName(getIndicatorId(block))}, <@printShift block "6" />) < 0)
        && (sqGetIndicatorValue(${getIndyShortName(getIndicatorId(block))}, <@printShift block "1" />) < sqGetIndicatorValue(${getIndyShortName(getIndicatorId(block))}, <@printShift block "2" />))
        && (sqGetIndicatorValue(${getIndyShortName(getIndicatorId(block))}, <@printShift block "3" />) < sqGetIndicatorValue(${getIndyShortName(getIndicatorId(block))}, <@printShift block "2" />))
        && (sqGetIndicatorValue(${getIndyShortName(getIndicatorId(block))}, <@printShift block "0" />) > sqGetIndicatorValue(${getIndyShortName(getIndicatorId(block))}, <@printShift block "1" />))
        && ((sqGetIndicatorValue(${getIndyShortName(getIndicatorId(block))}, <@printShift block "2" />) - sqGetIndicatorValue(${getIndyShortName(getIndicatorId(block))}, <@printShift block "1" />))><@printParam block "#Factor#" />)
        && ((sqGetIndicatorValue(${getIndyShortName(getIndicatorId(block))}, <@printShift block "2" />) - sqGetIndicatorValue(${getIndyShortName(getIndicatorId(block))}, <@printShift block "3" />))><@printParam block "#Factor#" />)
        && (sqGetIndicatorValue(${getIndyShortName(getIndicatorId(block))}, <@printShift block "0" />) > -50)