"""Print native SQX Source Code through the running producer web server.

Strategy XML bytes come from the databank ``.sqx``. EasyLanguage / MQL / Pseudo
Code are generated by StrategyQuant X ``sourcecode/print``, not by TraderCockpit.
"""

from __future__ import annotations

from zipfile import BadZipFile, ZipFile

from .sqx_custom_project import SqxCustomProjectTopologyError
from .sqx_custom_project_strategy import _resolved_strategy_archive
from .sqx_native_web import SqxNativeWebError, sqx_local_json
from .sqx_presets import SQX_BUILD
from .sqx_results_overview import ensure_databank_result


SQX_SOURCECODE_SCHEMA = "tc.sqx-sourcecode.v1"
SQX_SOURCECODE_CATALOG_SCHEMA = "tc.sqx-sourcecode-catalog.v1"
SQX_SOURCECODE_EA_SCHEMA = "tc.sqx-sourcecode-ea.v1"
SQX_SOURCECODE_API_PATH = "/api/sqx-sourcecode"
SOURCECODE_PRINT_PATH = "/sourcecode/print"
SOURCECODE_INIT_PATH = "/main/loadInitializationData"
SOURCECODE_SAVE_EA_PATH = "/sourcecode/saveEA"
SOURCECODE_DATA_PATH = "/sourcecode/getDataPath"
SOURCECODE_SAVE_MT_PATHS = "/sourcecode/saveMTPaths"
SOURCECODE_SETTINGS_PATH = "/main/getSettings"
_MT_PATH_KEYS = ("mt4InstallPath", "mt5InstallPath", "mt4DataPath", "mt5DataPath")
_PATH_MAX = 512

FORMAT_TO_TYPE = {
    "xml": "Strategy XML",
    "pseudo": "Pseudo Code(*.TXT)",
    "mq4": "Expert Advisor for MetaTrader4 (*.MQ4)",
    "mq5": "Expert Advisor for MetaTrader5 (*.MQ5)",
    "el": "EasyLanguage for Tradestation / MultiCharts (*.el)",
    "pla": "EasyLanguage for MultiCharts (*.pla)",
    "java": "Expert Advisor for JForex (*.java)",
}

_BOOL_FIELDS = (
    "useVariables",
    "symmetricVariables",
    "periodParams",
    "constantsParams",
    "shiftParams",
    "otherParams",
    "entryParams",
    "entryLogic",
    "exitParamsUsed",
    "exitParamsUnused",
    "booleanParams",
    "recommendedParams",
)
_PRINT_FIELDS = frozenset(
    {
        "project",
        "databank",
        "archive",
        "type",
        "format",
        "mmType",
        "parametrizeType",
        *_BOOL_FIELDS,
    }
)
_EA_FIELDS = frozenset({"project", "databank", "archive", "isMT4", "mmType", "parametrizeType", *_BOOL_FIELDS})
_XML_FALLBACK_GENERATOR = {
    "name": "Strategy XML",
    "key": "xml",
    "desc": "Native strategy_Portfolio.xml from this databank archive.",
    "extension": {"types": "xml", "name": "XML Document"},
}


def _flag(value: object, default: bool) -> bool:
    if value is None:
        return default
    if isinstance(value, bool):
        return value
    raise SqxCustomProjectTopologyError(
        "sourcecode_fields_invalid",
        "Source Code flags must be JSON booleans.",
    )


def _strategy_xml(sqx_home: object, project: str, databank: str, archive: str) -> tuple[str, str]:
    path = _resolved_strategy_archive(sqx_home, project, databank, archive)
    try:
        with ZipFile(path) as handle:
            text = handle.read("strategy_Portfolio.xml").decode("utf-8-sig")
    except (BadZipFile, KeyError, UnicodeDecodeError) as exc:
        raise SqxCustomProjectTopologyError(
            "strategy_xml_unreadable",
            "Archive strategy_Portfolio.xml could not be read as UTF-8.",
        ) from exc
    name = path.stem
    return name, text


def _resolve_type(payload: dict[str, object], generators: list[object] | None = None) -> str:
    type_name = payload.get("type")
    fmt = payload.get("format")
    if type_name is None and fmt is None:
        return "Strategy XML"
    if type_name is not None and not isinstance(type_name, str):
        raise SqxCustomProjectTopologyError("sourcecode_fields_invalid", "Source code type must be a string.")
    if fmt is not None and not isinstance(fmt, str):
        raise SqxCustomProjectTopologyError("sourcecode_fields_invalid", "Source code format must be a string.")
    names = []
    for item in generators or []:
        if isinstance(item, dict) and isinstance(item.get("name"), str):
            names.append(item["name"])
    if isinstance(type_name, str) and type_name:
        if names and type_name not in names and type_name not in FORMAT_TO_TYPE.values():
            mapped = FORMAT_TO_TYPE.get(type_name)
            if mapped:
                return mapped
        return type_name
    if isinstance(fmt, str) and fmt:
        return FORMAT_TO_TYPE.get(fmt) or fmt
    return "Strategy XML"


def _print_form(payload: dict[str, object], *, strategy_name: str, strategy_xml: str, code_type: str) -> dict[str, str]:
    parametrize = payload.get("parametrizeType", 0)
    if parametrize is None:
        parametrize = 0
    if isinstance(parametrize, bool) or not isinstance(parametrize, int) or parametrize not in {0, 1, 2}:
        raise SqxCustomProjectTopologyError(
            "sourcecode_fields_invalid",
            "parametrizeType must be 0 (recommended), 1 (own settings), or 2 (none).",
        )
    flags = {
        "useVariables": _flag(payload.get("useVariables"), True),
        "symmetricVariables": _flag(payload.get("symmetricVariables"), True),
        "periodParams": _flag(payload.get("periodParams"), True),
        "constantsParams": _flag(payload.get("constantsParams"), False),
        "shiftParams": _flag(payload.get("shiftParams"), False),
        "otherParams": _flag(payload.get("otherParams"), False),
        "entryParams": _flag(payload.get("entryParams"), False),
        "entryLogic": _flag(payload.get("entryLogic"), False),
        "exitParamsUsed": _flag(payload.get("exitParamsUsed"), True),
        "exitParamsUnused": _flag(payload.get("exitParamsUnused"), False),
        "booleanParams": _flag(payload.get("booleanParams"), False),
        "recommendedParams": _flag(payload.get("recommendedParams"), True),
    }
    if parametrize == 2:
        for key in flags:
            if key != "useVariables":
                flags[key] = False
    elif parametrize == 0:
        flags["recommendedParams"] = True
        flags["symmetricVariables"] = True
        flags["periodParams"] = True
        flags["exitParamsUsed"] = True
        flags["constantsParams"] = False
        flags["shiftParams"] = False
        flags["otherParams"] = False
        flags["entryParams"] = False
        flags["entryLogic"] = False
        flags["exitParamsUnused"] = False
        flags["booleanParams"] = False
    mm = payload.get("mmType") or "fromStrategy"
    if not isinstance(mm, str) or not mm or "\0" in mm:
        raise SqxCustomProjectTopologyError("sourcecode_fields_invalid", "mmType must be a native MM value.")
    form = {
        "project": str(payload["project"]),
        "databank": str(payload["databank"]),
        "strategy": strategy_name,
        "fileName": strategy_name,
        "type": code_type,
        "mmType": mm,
        "strategyXML": strategy_xml,
    }
    form.update({key: "true" if value else "false" for key, value in flags.items()})
    return form


def _folder_path(value: object) -> str:
    if value is None:
        return ""
    if not isinstance(value, str):
        raise SqxCustomProjectTopologyError(
            "sourcecode_fields_invalid",
            "MetaTrader paths must be strings.",
        )
    if "\0" in value or any(ord(ch) < 32 for ch in value) or len(value) > _PATH_MAX:
        raise SqxCustomProjectTopologyError(
            "sourcecode_fields_invalid",
            "MetaTrader path is not a single folder path.",
        )
    return value


def _export_ea_record(sqx_home: object, *, available: bool) -> dict[str, object]:
    paths = {key: "" for key in _MT_PATH_KEYS}
    if available:
        try:
            settings_payload = sqx_local_json(sqx_home, SOURCECODE_SETTINGS_PATH)
            settings = settings_payload.get("settings") if isinstance(settings_payload.get("settings"), dict) else {}
            for key in _MT_PATH_KEYS:
                value = settings.get(key)
                paths[key] = value if isinstance(value, str) else ""
        except SqxNativeWebError:
            pass
    return {
        "available": available,
        "platforms": ["MT4", "MT5"],
        **paths,
    }


def sourcecode_catalog_record(sqx_home: object) -> dict[str, object]:
    try:
        payload = sqx_local_json(sqx_home, SOURCECODE_INIT_PATH)
    except SqxNativeWebError as exc:
        return {
            "schema": SQX_SOURCECODE_CATALOG_SCHEMA,
            "source_build": SQX_BUILD,
            "producer": "unavailable",
            "reason_code": exc.code,
            "detail": exc.detail,
            "generators": [_XML_FALLBACK_GENERATOR],
            "mmTypes": [{"name": "From strategy", "value": "fromStrategy"}],
            "export_ea": _export_ea_record(sqx_home, available=False),
        }
    results = payload.get("results") if isinstance(payload.get("results"), dict) else {}
    source = results.get("sourceCode") if isinstance(results.get("sourceCode"), dict) else {}
    generators = source.get("engineTypes") if isinstance(source.get("engineTypes"), list) else []
    mm_types = source.get("mmTypes") if isinstance(source.get("mmTypes"), list) else []
    if not generators:
        generators = [_XML_FALLBACK_GENERATOR]
    if not mm_types:
        mm_types = [{"name": "From strategy", "value": "fromStrategy"}]
    return {
        "schema": SQX_SOURCECODE_CATALOG_SCHEMA,
        "source_build": SQX_BUILD,
        "producer": "sqx_local_web",
        "reason_code": None,
        "detail": None,
        "generators": generators,
        "mmTypes": mm_types,
        "export_ea": _export_ea_record(sqx_home, available=True),
    }


def print_sourcecode(sqx_home: object, payload: dict[str, object]) -> dict[str, object]:
    if set(payload) - _PRINT_FIELDS:
        raise SqxCustomProjectTopologyError(
            "sourcecode_fields_invalid",
            "Source Code print accepts only native print fields.",
        )
    project = payload.get("project")
    databank = payload.get("databank")
    archive = payload.get("archive")
    if not isinstance(project, str) or not isinstance(databank, str) or not isinstance(archive, str):
        raise SqxCustomProjectTopologyError(
            "sourcecode_fields_invalid",
            "Source Code print requires project, databank, and archive.",
        )
    code_type = _resolve_type(payload)
    strategy_name, strategy_xml = _strategy_xml(sqx_home, project, databank, archive)
    form = _print_form(payload, strategy_name=strategy_name, strategy_xml=strategy_xml, code_type=code_type)
    try:
        printed = sqx_local_json(sqx_home, SOURCECODE_PRINT_PATH, method="POST", fields=form)
    except SqxNativeWebError as exc:
        if code_type == "Strategy XML":
            return {
                "schema": SQX_SOURCECODE_SCHEMA,
                "source_build": SQX_BUILD,
                "producer": "archive",
                "type": code_type,
                "code": strategy_xml,
                "warning": None,
                "learnMoreURL": None,
                "success": "ok",
                "detail": exc.detail,
            }
        raise
    code = printed.get("code")
    if not isinstance(code, str):
        code = ""
    warning = printed.get("warning")
    learn = printed.get("learnMoreURL")
    return {
        "schema": SQX_SOURCECODE_SCHEMA,
        "source_build": SQX_BUILD,
        "producer": "sqx_local_web",
        "type": code_type,
        "code": code,
        "warning": warning if isinstance(warning, str) or warning is None else str(warning),
        "learnMoreURL": learn if isinstance(learn, str) or learn is None else None,
        "success": printed.get("success") if isinstance(printed.get("success"), str) else "ok",
        "detail": None,
    }


def save_ea(sqx_home: object, payload: dict[str, object]) -> dict[str, object]:
    body = {key: value for key, value in payload.items() if key not in {"type", "format"}}
    if set(body) - _EA_FIELDS:
        raise SqxCustomProjectTopologyError(
            "sourcecode_fields_invalid",
            "Save as EA accepts only native saveEA fields.",
        )
    project = body.get("project")
    databank = body.get("databank")
    archive = body.get("archive")
    is_mt4 = body.get("isMT4")
    if not isinstance(project, str) or not isinstance(databank, str) or not isinstance(archive, str):
        raise SqxCustomProjectTopologyError(
            "sourcecode_fields_invalid",
            "Save as EA requires project, databank, and archive.",
        )
    if not isinstance(is_mt4, bool):
        raise SqxCustomProjectTopologyError(
            "sourcecode_fields_invalid",
            "Save as EA isMT4 must be a JSON boolean.",
        )
    strategy_name, strategy_xml = _strategy_xml(sqx_home, project, databank, archive)
    form = _print_form(body, strategy_name=strategy_name, strategy_xml=strategy_xml, code_type="Strategy XML")
    form.pop("type", None)
    form.pop("fileName", None)
    form["isMT4"] = "true" if is_mt4 else "false"
    ensure_databank_result(sqx_home, project, databank, archive)
    saved = sqx_local_json(sqx_home, SOURCECODE_SAVE_EA_PATH, method="POST", fields=form)
    error = saved.get("error")
    return {
        "schema": SQX_SOURCECODE_EA_SCHEMA,
        "source_build": SQX_BUILD,
        "producer": "sqx_local_web",
        "success": error is None,
        "detail": None if error is None else str(error),
        "isMT4": is_mt4,
    }


def sourcecode_data_path(sqx_home: object, payload: dict[str, object]) -> dict[str, object]:
    if set(payload) - {"installPath", "isMT4"}:
        raise SqxCustomProjectTopologyError(
            "sourcecode_fields_invalid",
            "getDataPath accepts only installPath and isMT4.",
        )
    install = _folder_path(payload.get("installPath"))
    if not install:
        raise SqxCustomProjectTopologyError(
            "sourcecode_fields_invalid",
            "getDataPath requires installPath.",
        )
    is_mt4 = payload.get("isMT4")
    if not isinstance(is_mt4, bool):
        raise SqxCustomProjectTopologyError(
            "sourcecode_fields_invalid",
            "getDataPath isMT4 must be a JSON boolean.",
        )
    result = sqx_local_json(
        sqx_home,
        SOURCECODE_DATA_PATH,
        method="POST",
        fields={"installPath": install, "isMT4": "true" if is_mt4 else "false"},
    )
    path = result.get("dataPath")
    return {
        "schema": SQX_SOURCECODE_EA_SCHEMA,
        "source_build": SQX_BUILD,
        "producer": "sqx_local_web",
        "success": not result.get("error"),
        "dataPath": path if isinstance(path, str) else "",
        "detail": None if not result.get("error") else str(result.get("error")),
    }


def save_mt_paths(sqx_home: object, payload: dict[str, object]) -> dict[str, object]:
    if set(payload) - set(_MT_PATH_KEYS):
        raise SqxCustomProjectTopologyError(
            "sourcecode_fields_invalid",
            "saveMTPaths accepts only the four MetaTrader folder keys.",
        )
    fields = {key: _folder_path(payload.get(key)) for key in _MT_PATH_KEYS}
    result = sqx_local_json(sqx_home, SOURCECODE_SAVE_MT_PATHS, method="POST", fields=fields)
    error = result.get("error")
    return {
        "schema": SQX_SOURCECODE_EA_SCHEMA,
        "source_build": SQX_BUILD,
        "producer": "sqx_local_web",
        "success": error is None,
        "detail": None if error is None else str(error),
        **fields,
    }

