package SQ.Internal;

import com.strategyquant.lib.SQUtils;
import com.strategyquant.lib.ValuesMap;
import com.strategyquant.lib.XMLUtil;
import com.strategyquant.tradinglib.Blocks;
import com.strategyquant.tradinglib.Editor;
import com.strategyquant.tradinglib.IBlock;
import com.strategyquant.tradinglib.Parameter;
import com.strategyquant.tradinglib.TradingOption;
import com.strategyquant.tradinglib.Variable;
import com.strategyquant.tradinglib.Variables;
import com.strategyquant.tradinglib.options.TradingOptions;
import com.strategyquant.tradinglib.options.TradingOptionsList;
import com.strategyquant.tradinglib.project.ProjectConfigHelper;
import com.strategyquant.tradinglib.propertygrid.IPGParameter;
import java.lang.annotation.Annotation;
import java.lang.reflect.Field;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Iterator;
import java.util.List;
import org.apache.commons.lang3.StringUtils;
import org.jdom2.Element;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class VariablesTransformer {
   private static final Logger Log = LoggerFactory.getLogger(VariablesTransformer.class);
   public static final String ParamTypeLine = "ParamTypeLine";
   private static final String generatedAttrName = "autoGenerated";
   private static final String makeExternalAttrName = "makeExternal";
   private static final String ParamTypeUnknown = null;
   private XmlStrategy strategy;
   private boolean symmetryEnabled;
   private String minPeriod;
   private String minShift;

   public VariablesTransformer(XmlStrategy var1) {
      this.strategy = var1;
      this.symmetryEnabled = this.checkSymmetryEnabled();
      this.minPeriod = SQUtils.doubleToString(-1000003.0);
      this.minShift = SQUtils.doubleToString(-1000001.0);
   }

   private boolean checkSymmetryEnabled() {
      return true;
   }

   public void transformToVariables(boolean var1, ValuesMap var2) throws Exception {
      if (this.isTransformed()) {
         this.backToNumbers();
      }

      boolean var3;
      if (var2 == null) {
         var3 = false;
      } else {
         if (this.recognizeEmpty(var2)) {
            return;
         }

         var3 = var2.getBoolean("ParamTypeRecommended", false);
         if (var3) {
            var1 = true;
         }
      }

      Element var4 = this.strategy.getStrategyXml();
      ArrayList var5 = XMLUtil.getNestedElements(var4, "Rule");

      for (int var7 = 0; var7 < var5.size(); var7++) {
         Element var8 = (Element)var5.get(var7);
         VariablesTransformer.RuleType var9 = this.getRuleType(var8);
         ArrayList var10 = this.findItems(var8);

         for (int var11 = 0; var11 < var10.size(); var11++) {
            Element var12 = (Element)var10.get(var11);
            String var13 = var12.getAttributeValue("key");
            List var14 = var12.getChildren("Param");

            for (int var15 = 0; var15 < var14.size(); var15++) {
               Element var16 = (Element)var14.get(var15);
               String var17 = this.getParamKey(var16, var13);
               if (var17 != null) {
                  String var18 = var16.getAttributeValue("variable");
                  if (var18 != null && var18.equals("true")) {
                     String var19 = var16.getTextTrim();
                     Variable var20 = this.strategy.variables().get(var19);
                     if (var20 != null || this.strategy.variables().getById(var19) != null) {
                        this.fixMinMaxVariable(var16);
                        continue;
                     }

                     if (!var17.equals("#Shift#") && !var17.equals("#Type#")) {
                        this.fixMinMaxVariable(var16);
                        continue;
                     }

                     String var21 = var16.getAttributeValue("defaultValue");
                     if (var21 != null) {
                        var16.setText(var21);
                     } else {
                        var16.setText("0");
                     }

                     var16.setAttribute("variable", "false");
                  }

                  if (var16.getChildren().size() <= 0) {
                     String var31 = this.getParameterType(var16, var9, var13, var17, false, null, null);
                     if (!this.tryFixVariableAttributes(var16, var31)
                        && this.paramTypeToTransform(var31, var2, var3)
                        && (var31 != "ParamTypePeriod" || this.checkEntryLevels(var16, var2))) {
                        this.addVariable(var16, var1, var9, var13, var17, var31);
                     }
                  } else {
                     ArrayList var47 = XMLUtil.getNestedElements(var16, "Param");

                     for (int var49 = 0; var49 < var47.size(); var49++) {
                        Element var51 = (Element)var47.get(var49);
                        boolean var22 = false;
                        String var23 = this.getFormulaParentKey(var51);
                        if (var23 == null) {
                           var22 = true;
                        } else if (var23.contains(".PctValue") || var23.contains(".FixedValue") || var23.contains(".ATRBasedValue")) {
                           var22 = true;
                        }

                        if (var22) {
                           String var24 = this.getParamKey(var51, var13);
                           if (var24 != null) {
                              if (var24.equals("#Value#")) {
                                 Element var25 = var51.getParentElement();
                                 if (var25.getAttributeValue("key").contains("ATR")) {
                                    var24 = "Coef";
                                 } else {
                                    var24 = "";
                                 }
                              }

                              String var6;
                              if (var24.equals("#AtrPeriod#")) {
                                 var6 = "ParamTypeOtherParam";
                              } else {
                                 var6 = this.getParameterType(var16, var9, var13, var17, true, var23, var24);
                              }

                              if (!this.tryFixVariableAttributes(var51, var6) && this.paramTypeToTransform(var6, var2, var3)) {
                                 this.addVariable(var51, var1, var9, var13, var17 + var24, var6);
                              }
                           }
                        } else if (var23.equals("SQ.Formulas.Price.UseFormula")) {
                           String var56 = this.getParamKey(var51, var13);
                           if (var56 != null) {
                              String var30 = this.getParameterType(var16, var9, var13, var17, true, var23, var56);
                              if (!this.tryFixVariableAttributes(var51, var30)
                                 && this.paramTypeToTransform(var30, var2, var3)
                                 && (var30 != "ParamTypePeriod" || this.checkEntryLevels(var16, var2))) {
                                 this.addVariable(var51, var1, var9, var13, var17 + "EntryMult", var30);
                              }
                           }
                        }
                     }
                  }
               }
            }
         }
      }

      if (var2 == null || var2.getBoolean("ParamTypeTradingOptions", false)) {
         try {
            List var32 = TradingOptionsList.getInstance().getAvailableClasses();
            HashMap var33 = null;
            Element var34 = var4.getChild("TradingOptions");

            try {
               if (var34 != null) {
                  TradingOptions var35 = ProjectConfigHelper.getOptions(var34);
                  var33 = new HashMap();

                  for (int var37 = 0; var37 < var35.size(); var37++) {
                     TradingOption var39 = (TradingOption)var35.get(var37);
                     var33.put(var39.getClass().getSimpleName(), var39);
                  }
               }
            } catch (Exception var28) {
               Log.error("Cannot load strategy trading options", var28);
            }

            for (int var36 = 0; var36 < var32.size(); var36++) {
               TradingOption var38 = (TradingOption)var32.get(var36);
               String var40 = var38.getClass().getSimpleName();
               if (!var40.equals("SessionOption") && !var40.equals("StoreChartData") && !var40.equals("ComputeDailyStats")) {
                  ArrayList var41 = var38.getParams();
                  TradingOption var42 = null;
                  if (var33 != null && var33.containsKey(var40)) {
                     var42 = (TradingOption)var33.get(var40);
                  }

                  for (int var43 = 0; var43 < var41.size(); var43++) {
                     IPGParameter var44 = (IPGParameter)var41.get(var43);
                     String var45 = var44.getKey();
                     String var46 = var40 + "." + var45;
                     String var48 = var44.getName();
                     String var50 = "string";
                     String var52 = null;
                     if (var42 != null) {
                        try {
                           var52 = String.valueOf(var42.getParameterValue(var45));
                        } catch (Exception var26) {
                           Log.error("Cannot set variable '" + var46 + "'", var26);
                        }
                     }

                     try {
                        Field var53 = var38.getClass().getField(var45);
                        String var55 = var53.getType().getSimpleName();
                        Editor var57 = var53.getAnnotation(Editor.class);
                        Parameter var58 = var53.getAnnotation(Parameter.class);
                        if (var57 != null && var57.type() == 110) {
                           var50 = "time";
                        } else if (var55.equals(Boolean.class.getSimpleName()) || var55.equals(boolean.class.getSimpleName())) {
                           var50 = "boolean";
                        } else if (var55.equals(Integer.class.getSimpleName()) || var55.equals(int.class.getSimpleName())) {
                           var50 = "int";
                        } else if (var55.equals(Double.class.getSimpleName()) || var55.equals(double.class.getSimpleName())) {
                           var50 = "double";
                        } else if (var55.equals(String.class.getSimpleName())) {
                           var50 = "string";
                        } else {
                           Log.error("Unexpected trading option param class '" + var55 + "', param field '" + var53.getName() + "'.");
                        }

                        if (var52 == null) {
                           if (var58 != null) {
                              var52 = var58.defaultValue();
                           } else {
                              var52 = var44.print();
                           }
                        }
                     } catch (Exception var27) {
                        Log.error("Cannot load trading option variable " + var46, var27);
                     }

                     Variable var54 = new Variable(var46, var48, var50, var52, true, "ParamTypeTradingOptions", false);
                     this.strategy.variables().add(var54);
                  }
               }
            }
         } catch (Exception var29) {
            Log.error("Cannot load trading options variables", var29);
         }
      }

      this.generateVariablesXML();
   }

   private boolean checkEntryLevels(Element var1, ValuesMap var2) {
      if (var2 == null) {
         return true;
      }

      Element var3 = var1;
      boolean var4 = false;

      while (true) {
         Element var5 = var3.getParentElement();
         if (var5 == null) {
            break;
         }

         String var6 = var5.getAttributeValue("key");
         if (var6 != null && (var6.contains("EnterAt") || var6.contains("ReverseAt"))) {
            var4 = true;
            break;
         }

         var3 = var5;
      }

      return !var4 ? true : var2.getBoolean("ParamTypeEntryLevel");
   }

   private boolean recognizeEmpty(ValuesMap var1) {
      String[] var2 = var1.getAllKeys();

      for (int var3 = 0; var3 < var2.length; var3++) {
         if (var1.getBoolean(var2[var3], false)) {
            return false;
         }
      }

      return true;
   }

   private boolean IsSignalVariable(String var1) {
      Variable var2 = this.strategy.variables().get(var1);
      if (var2 != null) {
         ArrayList var3 = XMLUtil.getNestedElements(this.strategy.getStrategyXml(), "signal");

         for (int var4 = 0; var4 < var3.size(); var4++) {
            Element var5 = (Element)var3.get(var4);
            if (var5.getAttributeValue("variable").equals(var2.getId())) {
               return true;
            }
         }
      }

      return false;
   }

   private boolean tryFixVariableAttributes(Element var1, String var2) {
      String var3 = var1.getText();
      String var4 = var1.getAttributeValue("type");
      if (var3 != null) {
         if (var1.getAttributeValue("variable") == null) {
            Variable var5 = this.strategy.variables().get(var3);
            if (var5 != null) {
               if (!this.IsSignalVariable(var3)) {
                  var1.setAttribute("variable", "true");
               }

               if (var4 != null) {
                  var1.setAttribute("variableType", var4.toUpperCase());
               }

               var5.setParamType(var2);
               return true;
            }
         } else {
            Variable var6 = this.strategy.variables().get(var3);
            if (var6 != null) {
               return true;
            }
         }
      }

      return false;
   }

   private void fixMinMaxVariable(Element var1) {
      String var2 = var1.getText();
      if (var2 != null) {
         Variable var3 = this.strategy.variables().getById(var2);
         if (var3 != null) {
            double var4 = 2.147483647E9;
            double var6 = -2.147483647E9;
            String var8 = var1.getAttributeValue("controlType");
            if (var8 != null) {
               if (!var8.contains("jspinner") && var8.contains("combo")) {
                  String var9 = var1.getAttributeValue("values");
                  if (var9 == null) {
                     return;
                  }

                  String[] var10 = var9.split(",");
                  if (var10 == null || var10.length == 0) {
                     return;
                  }

                  for (int var11 = 0; var11 < var10.length; var11++) {
                     String[] var12 = var10[var11].split("=");
                     if (var12 != null && var12.length == 2) {
                        double var13 = Double.parseDouble(var12[1]);
                        if (var13 < var4) {
                           var4 = var13;
                        }

                        if (var13 > var6) {
                           var6 = var13;
                        }
                     }
                  }
               }

               if (var4 != 2.147483647E9 || var6 != -2.147483647E9) {
                  var3.setMinMax(var4, var6);
               }
            }
         }
      }
   }

   private String getFormulaParentKey(Element var1) {
      for (int var2 = 0; var2 < 50; var2++) {
         Element var3 = var1.getParentElement();
         if (var3 == null) {
            return null;
         }

         if (var3.getName().equals("Formula")) {
            return var3.getAttributeValue("key");
         }

         var1 = var3;
      }

      return null;
   }

   private boolean paramTypeToTransform(String var1, ValuesMap var2, boolean var3) {
      if (var1 == null) {
         return false;
      } else if (!var3 || !var1.equals("ParamTypePeriod") && !var1.equals("ParamTypeEntryLevel") && !var1.equals("ParamTypeExitUsed")) {
         return var2 == null ? true : var2.getBoolean(var1, false);
      } else {
         return true;
      }
   }

   private String getParameterType(Element var1, VariablesTransformer.RuleType var2, String var3, String var4, boolean var5, String var6, String var7) {
      if (!var4.contains("#BarsValid#") && !var4.contains("#ReplaceExisting#")) {
         String var8 = var1.getAttributeValue("type");
         if (var8 != null && var8.equals("boolean")) {
            return "ParamTypeBoolean";
         }

         if (var4.contains("Period#") || var4.startsWith("#Fast") || var4.startsWith("#Slow") || var4.startsWith("#Smooth") || var4.contains("#Period")) {
            return "ParamTypePeriod";
         }

         if (var4.equals("#Shift#")) {
            return "ParamTypeShift";
         }

         if (var4.equals("#Line#")) {
            return "ParamTypeLine";
         }

         if (var4.equals("#Value#")) {
            String var9 = var1.getAttributeValue("controlType");
            if (var9 != null && var9.equals("combo")) {
               return "ParamTypeLine";
            }
         }

         String var11 = var1.getAttributeValue("genMinValue");
         if (var11 != null) {
            if (var11.equals(this.minPeriod)) {
               return "ParamTypePeriod";
            }

            if (var11.equals(this.minShift)) {
               return "ParamTypeShift";
            }
         }

         if (var3.equals("Number") || var4.equals("#Level#")) {
            return "ParamTypeConstant";
         }

         if (!var5) {
            if (!var3.startsWith("EnterAt") && !var3.startsWith("EnterReverseAt")) {
               return var8.equals("int") && this.tryRecognizePeriodParam(var3, var4) ? "ParamTypePeriod" : "ParamTypeOtherParam";
            }

            if (var4.equals("#ExitAfterBars.ExitAfterBars#")) {
               String var10 = var1.getText();
               if (var10.equals("0")) {
                  return "ParamTypeExitUnused";
               }
            }

            return this.isUsed(var1) ? "ParamTypeExitUsed" : "ParamTypeExitUnused";
         } else {
            if (!var5) {
               return ParamTypeUnknown;
            }

            if (var6 != null && var6.equals("SQ.Formulas.Price.UseFormula")) {
               if (var7 == null || !var7.equals("#Number#")) {
                  return ParamTypeUnknown;
               } else {
                  return var3.equals("AssignVariable") ? ParamTypeUnknown : "ParamTypeEntryLevel";
               }
            } else {
               return this.isUsed(var1) ? "ParamTypeExitUsed" : "ParamTypeExitUnused";
            }
         }
      } else {
         return "ParamTypeEntryLogic";
      }
   }

   private boolean tryRecognizePeriodParam(String var1, String var2) {
      try {
         IBlock var3 = Blocks.get(var1);
         Class var4 = var3.getClass();
         var2 = var2.replace("#", "");
         Field[] var5 = var4.getFields();

         for (int var6 = 0; var6 < var5.length; var6++) {
            Field var7 = var5[var6];
            if (var7.getName().equals(var2)) {
               for (Annotation var11 : var7.getAnnotations()) {
                  if (var11 instanceof Parameter && ((Parameter)var11).isPeriod()) {
                     return true;
                  }
               }
            }
         }
      } catch (Exception var12) {
         if (var12.getMessage().contains("talib_")) {
            Log.debug("Error recognizing parameter type from class: " + var12.getMessage());
         } else {
            Log.error("Error recognizing parameter type from class: " + var12.getMessage());
         }
      }

      return false;
   }

   private boolean isUsed(Element var1) {
      String var2 = var1.getAttributeValue("isFormula");
      if (var2 != null && var2.equals("true")) {
         Element var5 = var1.getChild("Formula");
         String var6 = var5.getAttributeValue("key");
         return !var6.endsWith(".None");
      }

      String var3 = var1.getAttributeValue("defaultValue");
      if (var3 == null) {
         return true;
      }

      String var4 = var1.getValue();
      return var4 == null ? true : !var3.equals(var4);
   }

   public void backToNumbers() throws Exception {
      if (this.isTransformed()) {
         ArrayList var1 = XMLUtil.getNestedElements(this.strategy.getStrategyXml(), "Rule");

         for (int var2 = 0; var2 < var1.size(); var2++) {
            Element var3 = (Element)var1.get(var2);
            ArrayList var4 = this.findItems(var3);

            for (int var5 = 0; var5 < var4.size(); var5++) {
               Element var6 = (Element)var4.get(var5);
               String var7 = var6.getAttributeValue("key");
               List var8 = var6.getChildren("Param");

               for (int var9 = 0; var9 < var8.size(); var9++) {
                  Element var10 = (Element)var8.get(var9);
                  String var11 = this.getParamKey(var10, var7);
                  if (var11 != null) {
                     if (var10.getChildren().size() > 0) {
                        ArrayList var12 = XMLUtil.getNestedElements(var10, "Param");

                        for (int var13 = 0; var13 < var12.size(); var13++) {
                           Element var14 = (Element)var12.get(var13);
                           String var15 = this.getParamKey(var14, var7);
                           if (var15 != null) {
                              this.replaceVariableWithNumber(var14);
                           }
                        }
                     } else {
                        this.replaceVariableWithNumber(var10);
                     }
                  }
               }
            }
         }

         this.removeGeneratedVariables();
      }
   }

   private String addVariable(Element var1, boolean var2, VariablesTransformer.RuleType var3, String var4, String var5, String var6) {
      String var7 = var1.getAttributeValue("type");
      if (var7 == null) {
         if (!var1.getAttributeValue("key").equals("#Number#")) {
            return null;
         }

         var7 = "double";
      }

      if (var7.equals("data") || var7.equals("string")) {
         return null;
      }

      if (!var5.contains("Direction") && !var5.equals("#MagicNumber#")) {
         var5 = SQUtils.renameActionParams(var5);
         var5 = var5.replace("#", "");
         var1.setAttribute("variable", "true");
         String var8 = var1.getTextTrim();
         if (this.strategy.variables().getById(var8) != null) {
            return null;
         }

         if (var8.endsWith(".00")) {
            var8 = var8.substring(0, var8.length() - 3);
         }

         if (var8.contains(".")) {
            while (var8.endsWith("0")) {
               var8 = var8.substring(0, var8.length() - 1);
            }
         }

         if (var8.endsWith(".")) {
            var8 = var8.substring(0, var8.length() - 1);
         }

         String var9 = this.generateVariableName(var1, var2, var3, var4, var5, var8);
         if (this.strategy.variables().get(var9) == null) {
            Variable var10 = new Variable(var9, var9, var7, var8, true, var6, false);
            this.strategy.variables().add(var10);
            var1.setText(var9);
         } else {
            var1.setText(this.strategy.variables().get(var9).getId());
         }

         return var9;
      } else {
         return null;
      }
   }

   private String generateVariableName(Element var1, boolean var2, VariablesTransformer.RuleType var3, String var4, String var5, String var6) {
      if (var3.equals(VariablesTransformer.RuleType.UNKNOWN)) {
         var2 = true;
      }

      String var7 = "";
      String var8 = null;
      if (var2) {
         String var9 = Blocks.getOppositeBlockKey(var4);
         if (!var9.equals(var4)) {
            var8 = this.findSameString(var4, var9);
         }
      } else {
         if (var3.equals(VariablesTransformer.RuleType.TRADING_SIGNALS)) {
            var3 = this.recognizeRuleTypeFromElement(var1, var3);
         }

         var7 = var3.equals(VariablesTransformer.RuleType.LONG) ? "Long" : "Short";
      }

      if (var4.contains("EnterAt")) {
         var4 = "";
      }

      if (var4.equals(var5)) {
         var7 = var7 + (var8 != null ? var8 : var4);
      } else {
         var7 = var7 + (var8 != null ? var8 : var4) + var5;
      }

      String[] var16 = var5.split("\\.");
      if (var16.length == 2) {
         if (var16[0].equals(var16[1])) {
            var5 = var16[0];
         } else if (var16[1].contains(var16[0])) {
            var5 = var16[1].replace(var16[0], "");
         }
      }

      int var10 = 1;
      String var11 = this.shortenName(var7 + var10);

      for (Variable var12 = this.strategy.variables().get(var11); var12 != null && !var12.getValue().equals(var6); var12 = this.strategy.variables().get(var11)) {
         var11 = this.shortenName(var7 + ++var10);
      }

      return var11.replace(".", "_");
   }

   private VariablesTransformer.RuleType recognizeRuleTypeFromElement(Element var1, VariablesTransformer.RuleType var2) {
      Element var3 = XMLUtil.findFirstParent(var1, "signal");
      if (var3 == null) {
         return var2;
      }

      String var4 = var3.getAttributeValue("variable");
      if (var4 == null) {
         return var2;
      }

      switch (var4) {
         case "33333333-1111-1111-3333-333333333333":
            return VariablesTransformer.RuleType.LONG;
         case "33333333-1111-2222-3333-333333333333":
            return VariablesTransformer.RuleType.LONG;
         case "33333333-2222-1111-3333-333333333333":
            return VariablesTransformer.RuleType.SHORT;
         case "33333333-2222-2222-3333-333333333333":
            return VariablesTransformer.RuleType.SHORT;
         default:
            return var2;
      }
   }

   private String findSameString(String var1, String var2) {
      StringBuilder var3 = new StringBuilder();

      for (int var5 = 0; var5 < Math.min(var1.length(), var2.length()); var5++) {
         char var4;
         if ((var4 = var1.charAt(var5)) == var2.charAt(var5)) {
            var3.append(var4);
         }
      }

      return var3.toString();
   }

   private String shortenName(String var1) {
      if (var1.length() <= 20) {
         return var1;
      }

      String[] var2 = StringUtils.splitByCharacterTypeCamelCase(var1);

      for (int var3 = var2.length - 1; var3 > 0; var3--) {
         var2[var3] = SQUtils.shortenWord(var2[var3], 3);
         if (this.checkWordsSize(var2) <= 20) {
            break;
         }
      }

      StringBuilder var5 = new StringBuilder();

      for (int var4 = 0; var4 < var2.length; var4++) {
         var5.append(var2[var4]);
      }

      return var5.toString();
   }

   private int checkWordsSize(String[] var1) {
      int var2 = 0;

      for (int var3 = 0; var3 < var1.length; var3++) {
         var2 += var1[var3].length();
      }

      return var2;
   }

   private void generateVariablesXML() throws Exception {
      Element var1 = this.getChildElem(this.getChildElem(this.strategy.getStrategyXml(), "Strategy"), "Variables");
      var1.removeContent();
      Variables var2 = this.strategy.variables();

      for (int var3 = 0; var3 < var2.size(); var3++) {
         Variable var4 = (Variable)var2.get(var3);
         Element var5 = var4.getXML().detach();
         if (var4.isAutoGenerated()) {
            var5.setAttribute("autoGenerated", "true");
         }

         if (var4.isMakeExternal()) {
            var5.setAttribute("makeExternal", "true");
         }

         var1.addContent(var5);
      }
   }

   private void replaceVariableWithNumber(Element var1) {
      String var2 = var1.getTextTrim();
      if (this.strategy.variables().get(var2) != null) {
         Variable var3 = this.strategy.variables().get(var2);
         if (var3 != null) {
            if (var3.isAutoGenerated()) {
               var1.setText(this.strategy.variables().get(var2).getValue());
               var1.setAttribute("variable", "false");
            } else {
               Element var4 = var3.getXML();
               if (var4 != null && XMLUtil.elementIs(var4, "autoGenerated")) {
                  var1.setText(var3.getValue());
                  var1.setAttribute("variable", "false");
               }
            }
         }
      }
   }

   private void removeGeneratedVariables() throws Exception {
      Element var1 = this.getChildElem(this.getChildElem(this.strategy.getStrategyXml(), "Strategy"), "Variables");
      Iterator var2 = var1.getChildren("variable").iterator();

      while (var2.hasNext()) {
         Element var3 = (Element)var2.next();
         if (XMLUtil.elementIs(var3, "autoGenerated") && XMLUtil.elementIsNot(var3, "makeExternal")) {
            var2.remove();
         }
      }

      Iterator var6 = this.strategy.variables().iterator();

      while (var6.hasNext()) {
         Variable var4 = (Variable)var6.next();
         Element var5 = var4.getXML();
         if (XMLUtil.elementIs(var5, "autoGenerated") && XMLUtil.elementIsNot(var5, "makeExternal") && var4.isAutoGenerated()) {
            var6.remove();
         }
      }
   }

   private Element getChildElem(Element var1, String var2) throws Exception {
      Element var3 = var1.getChild(var2);
      if (var3 == null) {
         throw new Exception("Project config doesn't contain '" + var2 + "' element");
      } else {
         return var3;
      }
   }

   private VariablesTransformer.RuleType getRuleType(Element var1) throws Exception {
      String var2 = var1.getAttributeValue("name");
      if (var2 == null) {
         throw new Exception("Rule doesn't have a name");
      } else if (var2.startsWith("Long")) {
         return VariablesTransformer.RuleType.LONG;
      } else if (var2.startsWith("Short")) {
         return VariablesTransformer.RuleType.SHORT;
      } else if (var2.startsWith("Trading signals")) {
         return VariablesTransformer.RuleType.TRADING_SIGNALS;
      } else {
         return var2.startsWith("Explore") ? VariablesTransformer.RuleType.EXPLORE : VariablesTransformer.RuleType.UNKNOWN;
      }
   }

   private ArrayList<Element> findItems(Element var1) {
      ArrayList var2 = new ArrayList();
      ArrayList var3 = XMLUtil.getNestedElements(var1, "Item");

      for (int var4 = 0; var4 < var3.size(); var4++) {
         Element var5 = (Element)var3.get(var4);
         if (this.itemValid(var5)) {
            var2.add(var5);
         }
      }

      return var2;
   }

   private boolean itemValid(Element var1) {
      String var2 = var1.getAttributeValue("key");
      return var2 != null && !var2.equals("AND") && !var2.equals("OR");
   }

   private String getParamKey(Element var1, String var2) {
      String var3 = var1.getAttributeValue("key");
      String var4 = var1.getAttributeValue("type");
      if (var3 == null) {
         Log.error("Parameter of item '" + var2 + "' doesn't have key attribute");
      } else if (!this.paramNotAllowed(var3, var2)) {
         if (var4 == null) {
            if (var3.equals("#Number#")) {
               return var3;
            }

            Log.error("Parameter '{}' doesn't have type attribute", var3);
         } else if (!var4.equals("unknown")) {
            return var3;
         }
      }

      return null;
   }

   private boolean paramNotAllowed(String var1, String var2) {
      return var1.equals("#MagicNumber#")
         || var1.equals("#ComputedFrom#")
         || var2.startsWith("EnterAt") && var1.equals("#Direction#")
         || var2.startsWith("EnterAt") && var1.equals("#Size#");
   }

   private boolean isTransformed() {
      try {
         Element var1 = this.getChildElem(this.getChildElem(this.strategy.getStrategyXml(), "Strategy"), "Variables");
         if (var1 != null) {
            for (Element var3 : var1.getChildren("variable")) {
               if (XMLUtil.elementIsNot(var3, "makeExternal")) {
                  return true;
               }
            }
         }
      } catch (Exception var4) {
         Log.error("Error while checking transformed state. ", var4);
      }

      return false;
   }

   public boolean isSymmetryEnabled() {
      return this.symmetryEnabled;
   }

   private enum RuleType {
      LONG,
      SHORT,
      UNKNOWN,
      TRADING_SIGNALS,
      EXPLORE;
   }
}
