package SQ.Internal;

import com.strategyquant.tradinglib.StrategyBase;
import com.strategyquant.tradinglib.Variable;
import com.strategyquant.tradinglib.indicator.IndicatorsObj;
import com.strategyquant.tradinglib.optimization.IStrategyModifier;
import com.strategyquant.tradinglib.optimization.OptimizationSettings;
import com.strategyquant.tradinglib.optimization.Parameter;
import com.strategyquant.tradinglib.optimization.StrategyParamData;
import java.text.DecimalFormat;
import org.jdom2.Element;

public class XmlStrategyModifier implements IStrategyModifier {
   public StrategyParamData createStrategyVariation(StrategyBase var1, OptimizationSettings var2, short[] var3) throws Exception {
      if (!(var1 instanceof XmlStrategy)) {
         throw new Exception("Not implemeted yet!");
      }

      XmlStrategy var4 = new XmlStrategy(var1.getStrategyXml().clone(), var1.getStrategyName());
      StringBuilder var5 = new StringBuilder();
      DecimalFormat var6 = new DecimalFormat("#.######");

      for (int var7 = 0; var7 < var2.parameters.size(); var7++) {
         Parameter var8 = (Parameter)var2.parameters.get(var7);
         short var9 = -1;
         if (var8.isUsed()) {
            var9 = var3[var7];
         }

         double var10 = var8.getValueByIndex(var9);
         if (var4.variables().canSetValue(var8.getName())) {
            var4.variables().setValue(var8.getName(), var10);
         }

         if (var8.isUsed()) {
            String var12 = var6.format(var10).replace(",", ".");
            if (var8.getType() == 2) {
               var12 = var12.equals("1") ? "true" : "false";
            }

            var5.append(var8.getName());
            var5.append("=");
            var5.append(var12);
            var5.append(",");
         }
      }

      for (int var13 = var4.variables().size() - 1; var13 >= 0; var13--) {
         Variable var14 = (Variable)var4.variables().get(var13);
         if (var14.getParamType() != null && var14.getParamType().equals("ParamTypeTradingOptions")) {
            boolean var15 = true;

            for (int var16 = 0; var16 < var2.parameters.size(); var16++) {
               Parameter var11 = (Parameter)var2.parameters.get(var16);
               if (var11.getName().equals(var14.getName())) {
                  var15 = !var11.isUsed();
                  break;
               }
            }

            if (var15) {
               var4.variables().remove(var13);
            }
         }
      }

      this.regenerateVariablesXML(var4);
      return new StrategyParamData(var4, var5.toString());
   }

   private void regenerateVariablesXML(XmlStrategy var1) throws Exception {
      Element var2 = var1.getStrategyXml().getChild("Strategy").getChild("Variables");
      var2.removeContent();

      for (int var3 = 0; var3 < var1.variables().size(); var3++) {
         Variable var4 = (Variable)var1.variables().get(var3);
         Element var5 = var4.getXML().detach();
         if (var4.isAutoGenerated()) {
            var5.setAttribute("autoGenerated", "true");
         }

         var2.addContent(var5);
      }
   }

   public StrategyBase createStrategyFromXml(Element var1, String var2) throws Exception {
      return new XmlStrategy(var1, var2);
   }

   public IndicatorsObj createIndicatorsObject(StrategyBase var1) {
      return new Indicators(var1);
   }
}
