package com.strategyquant.tradinglib.strategy.xml;

import com.strategyquant.datalib.data.DataManager;
import com.strategyquant.lib.SQUtils;
import com.strategyquant.lib.XMLUtil;
import com.strategyquant.lib.app.MainApp;
import com.strategyquant.tradinglib.BlockDefinitionException;
import com.strategyquant.tradinglib.Variable;
import com.strategyquant.tradinglib.Variables;
import com.strategyquant.tradinglib.blocks.random.BlocksConfig;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.function.Function;
import java.util.stream.Collectors;
import org.apache.commons.lang3.StringUtils;
import org.jdom2.Attribute;
import org.jdom2.Element;
import org.jdom2.JDOMException;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class StrategyFixer {
   public static final Logger Log = LoggerFactory.getLogger("StrategyFixer");
   public static final String currentVersion = "3.9.133";
   private static HashMap<String, String> blockCategoryTypes = new HashMap<>();
   private static Map<String, List<Attribute>> itemAttributes;

   public static Element fixStrategy(String var0) throws Exception {
      var0 = fixAutogeneratedVariables(var0);
      if (checkVersion(var0)) {
         Element var10 = XMLUtil.stringToElement(var0);
         fixAskBidSymbols(var10);
         fixStockpickerLongShort(var10);
         fixSRPercentRankIndicator(var10);
         fixRandomizedVariables(var10);
         return var10;
      }

      loadCategoryTypesAndAttributes();
      var0 = SQUtils.removeUTF8BOM(var0);
      var0 = SQUtils.removeXmlns(var0);
      var0 = SQUtils.fixRenamedActionParams(var0);
      var0 = SQUtils.fixHeikenAshi(var0);
      var0 = StringUtils.replaceAll(var0, "help=\".*?\"", "");
      var0 = replaceChikouSpan(var0);
      Element var1 = XMLUtil.stringToElement(var0);
      if (!checkVersion(var1, "3.9.133")) {
         fixShifts(var1);
      }

      fixCategoryTypes(var1);
      fixMissingAttributes(var1);
      fixMoneyManagement(var1);
      fixAskBidSymbols(var1);
      fixHighestLowestInRange(var1);
      fixStockpickerLongShort(var1);
      fixSRPercentRankIndicator(var1);
      Variables var2 = new Variables(var1);
      fixMissingVariables(var1, var2);
      return var1;
   }

   private static String fixAutogeneratedVariables(String var0) {
      return var0.replaceAll("autoGenerated=\"true\"", "");
   }

   private static void fixSRPercentRankIndicator(Element var0) {
      try {
         ArrayList var1 = new ArrayList();
         findAllSRPercentRank(var0, var1);
         if (var1 != null && var1.size() > 0) {
            for (int var2 = 0; var2 < var1.size(); var2++) {
               Element var3 = (Element)var1.get(var2);
               List var4 = var3.getChildren("Param");

               for (int var5 = 0; var5 < var4.size(); var5++) {
                  Element var6 = (Element)var4.get(var5);
                  String var7 = var6.getAttributeValue("key");
                  if (var7 != null && var7.equals("#Lenght#")) {
                     var6.setAttribute("key", "#Length#");
                     var6.setAttribute("name", "Length");
                  }
               }
            }
         }
      } catch (Exception var8) {
         Log.error("Error while evaluating method fixSRPercentRankIndicator() - " + var8.getMessage(), var8);
      }
   }

   private static void findAllSRPercentRank(Element var0, ArrayList<Element> var1) {
      List var2 = var0.getChildren();
      if (var2 != null && var2.size() > 0) {
         for (int var3 = 0; var3 < var2.size(); var3++) {
            Element var4 = (Element)var2.get(var3);
            if (var4.getName().equals("Item")) {
               String var5 = var4.getAttributeValue("key");
               if (var5 == null) {
                  continue;
               }

               if (var5.equals("SRPercentRank")
                  || var5.equals("SRPercRankAboveLevel")
                  || var5.equals("SRPercRankAboveLevelXBars")
                  || var5.equals("SRPercRankBelowLevel")
                  || var5.equals("SRPercRankBelowLevelXBars")) {
                  var1.add(var4);
               }
            }

            findAllSRPercentRank(var4, var1);
         }
      }
   }

   private static void fixStockpickerLongShort(Element var0) {
      String var1 = "<Item customSnippet=\"false\" key=\"Abs\" name=\"(ABS) Absolute value\" display=\"Abs(#Value#)\" returnType=\"pricenumber\" help=\"Absolute value of a number\" ignoreInBuilder=\"true\" mI=\"Functions\" categoryType=\"other\">  <Block key=\"#Value#\" name=\"Value\" type=\"value\" controlType=\"value\"/></Item>";

      try {
         List var2 = var0.getChild("Strategy").getChild("Rules").getChild("Events").getChild("Event").getChildren("Rule");

         for (int var3 = 0; var3 < var2.size(); var3++) {
            Element var4 = (Element)var2.get(var3);
            if (var4.getAttributeValue("type").equals("StockpickerPS") && var4.getAttributeValue("name").equals("Position Score")) {
               var4.setAttribute("name", "Position Score Long");
               List var5 = var4.getChild("Value").getChildren("Item");

               for (int var6 = 0; var6 < var5.size(); var6++) {
                  Element var7 = (Element)var5.get(var6);
                  List var8 = var7.getChildren("Param");
                  if (var8.size() == 3
                     && ((Element)var8.get(0)).getAttributeValue("name").equals("PositionScore")
                     && ((Element)var8.get(1)).getAttributeValue("name").equals("Value")) {
                     Element var9 = ((Element)var8.get(1)).getChild("Formula").getChild("Block");
                     Element var10 = XMLUtil.stringToElement(var1);
                     var10.getChild("Block").addContent(((Element)var9.getChildren().get(0)).detach());
                     var9.addContent(var10);
                  }
               }

               Element var13 = var4.clone();
               var13.setAttribute("name", "Position Score Short");
               var5 = var13.getChild("Value").getChildren("Item");

               for (int var14 = 0; var14 < var5.size(); var14++) {
                  Element var15 = (Element)var5.get(var14);
                  List var16 = var15.getChildren("Param");
                  if (var16.size() == 3
                     && ((Element)var16.get(0)).getAttributeValue("name").equals("MaxOpenPositions")
                     && ((Element)var16.get(1)).getAttributeValue("name").equals("Value")) {
                     ((Element)var16.get(1)).setText("0");
                  }
               }

               var2.add(var13);
               break;
            }
         }
      } catch (Exception var11) {
         Log.debug("Error while fixing Stockpicker PS Long/Short.", var11);
      }
   }

   private static String replaceChikouSpan(String var0) {
      try {
         for (int var1 = var0.indexOf("<Item key=\"Ichimoku\"", 0); var1 > 0; var1 = var0.indexOf("<Item key=\"Ichimoku\"", var1 + 1)) {
            int var2 = var0.indexOf("<Param key=\"#Line#\"", var1);
            if (var2 < 0) {
               break;
            }

            int var3 = var0.indexOf("</Param>", var2);
            if (var3 < 0) {
               break;
            }

            int var4 = Integer.parseInt(var0.substring(var3 - 1, var3));
            if (var4 == 4) {
               int var5 = var0.indexOf(">", var1 + 1);
               int var6 = var0.indexOf("</Item>", var1);
               int var7 = var0.indexOf("</Param>", var1);
               int var8 = var0.indexOf("<Param key=\"#KijunPeriod#\"", var1);
               int var9 = var0.indexOf(">", var8);
               int var10 = var0.indexOf("<", var9);
               int var11 = Integer.parseInt(var0.substring(var9 + 1, var10));
               int var12 = var0.indexOf("<Param key=\"#Shift#\"", var1);
               int var13 = var0.indexOf(">", var12);
               int var14 = var0.indexOf("<", var13);
               int var15 = Integer.parseInt(var0.substring(var13 + 1, var14));
               int var16 = var15 - var11;
               if (var16 < 0) {
                  var0 = var0.substring(0, var1)
                     + "<Item key=\"Number\" name=\"(NUM) Number\" display=\"#Number#\" help=\"Number constant\" mI=\"Other\" returnType=\"number\" categoryType=\"other\" notFirstValue=\"true\" notice=\"ChikouSpanReplacement\"><Param key=\"#Number#\" name=\"Number\" type=\"double\" defaultValue=\"0\" controlType=\"jspinner\" minValue=\"-999999999\" maxValue=\"999999999\" step=\"1\" builderStep=\"1\">0</Param>"
                     + var0.substring(var6);
               } else {
                  var0 = var0.substring(0, var1)
                     + "<Item key=\"Close\" name=\"(C) Close\" display=\"Close[#Shift#]\" mI=\"Price\" notice=\"ChikouSpanReplacement\">"
                     + var0.substring(var5 + 1);
                  var0 = var0.substring(0, var7 + "</Param>".length() + 1) + var0.substring(var12, var13 + 1) + var16 + "</Param>" + var0.substring(var6);
               }
            }
         }
      } catch (Exception var17) {
         Log.error("Error while replacing ChikouSpan blocks", var17);
      }

      return var0;
   }

   private static void fixMissingVariables(Element var0, Variables var1) {
      if (!var0.getName().equals("CustomBlocks")) {
         List var2 = var0.getChildren();
         if (var2 != null) {
            for (int var3 = 0; var3 < var2.size(); var3++) {
               Element var4 = (Element)var2.get(var3);
               if (var4.getName().equals("Param")) {
                  String var5 = var4.getAttributeValue("variable");
                  String var6 = var4.getAttributeValue("controlType");
                  if (shouldRemoveInvalidVariableAttribute(var4, var5)) {
                     var4.removeAttribute("variable");
                     var4.removeAttribute("variableType");
                     continue;
                  }

                  if (var5 != null && var5.equalsIgnoreCase("true")) {
                     String var7 = var4.getAttributeValue("generate");
                     if (var7 != null && var7.equals("random")) {
                        var4.setAttribute("variable", "false");
                        if (var5 != null) {
                           var5 = "false";
                        }
                     }
                  }

                  if ((var6 != null && var6.startsWith("comboVar") || var5 != null && var5.equalsIgnoreCase("true")) && var5 == null) {
                     String var11 = var4.getAttributeValue("type");
                     String var8 = var4.getAttributeValue("key");
                     Variable var9 = null;
                     if (var8.contains("MagicNumber")) {
                        String var10 = var4.getText();
                        if (var6.equals("comboVarsWithAny") && !var10.equals("0") && !var10.equals("Any")) {
                           var9 = findExistingVar(var11, "Magic", var1);
                        }
                     } else {
                        var9 = findExistingVar(var11, null, var1);
                     }

                     if (var9 != null) {
                        var4.setAttribute("variable", "true");
                        var4.setAttribute("variableType", var9.translateType(var9.getInternalType()));
                        var4.setText(var9.getId());
                     }
                  }
               }

               if (var4.getChildren() != null) {
                  fixMissingVariables(var4, var1);
               }
            }
         }
      }
   }

   private static void fixRandomizedVariables(Element var0) {
      if (!var0.getName().equals("CustomBlocks")) {
         List var1 = var0.getChildren();
         if (var1 != null) {
            for (int var2 = 0; var2 < var1.size(); var2++) {
               Element var3 = (Element)var1.get(var2);
               if (var3.getName().equals("Param")) {
                  String var4 = var3.getAttributeValue("variable");
                  String var5 = var3.getAttributeValue("controlType");
                  if (shouldRemoveInvalidVariableAttribute(var3, var4)) {
                     var3.removeAttribute("variable");
                     var3.removeAttribute("variableType");
                     var4 = null;
                  }

                  if (var4 != null && var4.equalsIgnoreCase("true")) {
                     String var6 = var3.getAttributeValue("generate");
                     if (var6 != null && var6.equals("random")) {
                        var3.setAttribute("variable", "false");
                        if (var4 != null) {
                           var4 = "false";
                        }
                     }
                  }
               }

               if (var3.getChildren() != null) {
                  fixRandomizedVariables(var3);
               }
            }
         }
      }
   }

   private static boolean shouldRemoveInvalidVariableAttribute(Element var0, String var1) {
      if (var1 != null && var1.equalsIgnoreCase("true")) {
         String var2 = StringUtils.trimToEmpty(var0.getText());
         if (var2.isEmpty()) {
            return false;
         }

         try {
            double var3 = Double.parseDouble(var2);
            return Double.isFinite(var3);
         } catch (Exception var5) {
            return false;
         }
      } else {
         return false;
      }
   }

   private static Variable findExistingVar(String var0, String var1, Variables var2) {
      if (var2 == null) {
         return null;
      }

      if (var1 != null) {
         for (int var3 = 0; var3 < var2.size(); var3++) {
            Variable var4 = var2.get(var3);
            if (var4.getName().contains(var1)) {
               return var4;
            }
         }
      }

      for (int var5 = 0; var5 < var2.size(); var5++) {
         Variable var6 = var2.get(var5);
         if (var6.getType().equals(var0)) {
            return var6;
         }
      }

      return null;
   }

   private static void fixAskBidSymbols(Element var0) {
      List var1 = var0.getChildren();
      if (var1 != null) {
         for (int var2 = 0; var2 < var1.size(); var2++) {
            Element var3 = (Element)var1.get(var2);
            if (var3.getName().equals("Item")) {
               String var4 = var3.getAttributeValue("key");
               if (var4 != null && (var4.equals("Ask") || var4.equals("Bid"))) {
                  Element var5 = XMLUtil.getItemParameterNoException(var3, "#Symbol#");
                  if (var5 != null) {
                     String var6 = var5.getText();
                     if (var6 != null && !var6.equals("Current") && !DataManager.checkDataExists("History", var6)) {
                        Log.info("Symbol {} not found, changing to 'Current'", var6);
                        var5.setText("Current");
                     }
                  }
               }
            }

            if (var3.getChildren() != null) {
               fixAskBidSymbols(var3);
            }
         }
      }
   }

   private static void fixHighestLowestInRange(Element var0) {
      List var1 = var0.getChildren();
      if (var1 != null) {
         for (int var2 = 0; var2 < var1.size(); var2++) {
            Element var3 = (Element)var1.get(var2);
            if (var3.getName().equals("Item")) {
               String var4 = var3.getAttributeValue("key");
               if (var4 != null && (var4.equals("HighestInRange") || var4.equals("LowestInRange"))) {
                  fixTimeParam(XMLUtil.getItemParameterNoException(var3, "#TimeFrom#"));
                  fixTimeParam(XMLUtil.getItemParameterNoException(var3, "#TimeTo#"));
               }
            }

            if (var3.getChildren() != null) {
               fixHighestLowestInRange(var3);
            }
         }
      }
   }

   private static void fixTimeParam(Element var0) {
      if (var0 != null) {
         String var1 = var0.getAttributeValue("type");
         if (var1.equals("int")) {
            return;
         }

         int var2 = 0;
         String var3 = var0.getText();
         if (var3 != null) {
            try {
               var2 = getHHMM(var3);
            } catch (Exception var5) {
            }

            var0.setText("" + var2);
         }

         var0.setAttribute("type", "int");
         var0.setAttribute("defaultValue", "0");
         var0.setAttribute("controlType", "jspinnerVar");
         var0.setAttribute("minValue", "0");
         var0.setAttribute("maxValue", "2359");
      }
   }

   private static int getHHMM(String var0) throws Exception {
      try {
         String[] var1 = var0.split(":");
         int var2 = Integer.parseInt(var1[0]);
         int var3 = Integer.parseInt(var1[1]);
         return var2 * 100 + var3;
      } catch (Exception var4) {
         throw new Exception("Invalid time format (" + var0 + "), must be HH:MM");
      }
   }

   public static void fixMissingAttributes(Element var0) throws Exception {
      ArrayList var1 = XMLUtil.getNestedElements(var0, "Item");

      for (int var2 = 0; var2 < var1.size(); var2++) {
         Element var3 = (Element)var1.get(var2);
         String var4 = var3.getAttributeValue("key");
         if (var4 != null) {
            List var5 = itemAttributes.get(var4);
            if (var5 != null) {
               addMissingAttributes(var3, var5);
            }
         }
      }
   }

   public static void removeRandomGenerateAttributes(Element var0) {
      ArrayList var1 = XMLUtil.getNestedElements(var0, "Param");

      for (int var2 = 0; var2 < var1.size(); var2++) {
         Element var3 = (Element)var1.get(var2);
         String var4 = var3.getAttributeValue("generate");
         if (var4 != null) {
            var3.removeAttribute("generate");
         }
      }
   }

   private static void addMissingAttributes(Element var0, List<Attribute> var1) {
      List var2 = var0.getAttributes();
      Set var3 = var2.stream().map(Attribute::getName).collect(Collectors.toSet());
      Map var4 = var1.stream().collect(Collectors.toMap(Attribute::getName, Function.identity()));

      for (String var6 : var4.keySet()) {
         if (!var3.contains(var6)) {
            var0.getAttributes().add(new Attribute(var6, ((Attribute)var4.get(var6)).getValue()));
         }
      }
   }

   public static boolean checkVersion(String var0) {
      try {
         int var1 = var0.indexOf("<StrategyFile ");
         if (var1 < 0) {
            return false;
         }

         int var2 = var0.indexOf("Version=", var1);
         if (var2 < 0) {
            return false;
         }

         int var3 = var0.indexOf("\"", var2 + 9);
         if (var3 < 0) {
            return false;
         }

         String var4 = var0.substring(var2 + 9, var3);
         return checkVersionString(var4, "3.9.133");
      } catch (Exception var5) {
         Log.error("Cannot check strategy version (2).", var5);
         return false;
      }
   }

   public static boolean checkVersion(Element var0) {
      return checkVersion(var0, "3.9.133");
   }

   public static boolean checkVersion(Element var0, String var1) {
      try {
         String var2 = var0.getAttributeValue("Version");
         return var2 == null ? false : checkVersionString(var2, var1);
      } catch (Exception var3) {
         Log.error("Cannot check strategy version (2).", var3);
         return false;
      }
   }

   public static void setCurrentVersion(Element var0) {
      var0.setAttribute("Version", "3.9.133");
      var0.setAttribute("AppVersion", MainApp.printFullAppVersion());
   }

   private static boolean checkVersionString(String var0, String var1) {
      try {
         String[] var2 = var0.split("\\.");
         String[] var3 = var1.split("\\.");

         for (int var4 = 0; var4 < var3.length; var4++) {
            if (var4 < var2.length && Integer.parseInt(var2[var4]) < Integer.parseInt(var3[var4])) {
               return false;
            }
         }

         return var2.length == var3.length;
      } catch (Exception var5) {
         Log.error("Cannot check strategy version (3).", var5);
         return false;
      }
   }

   public static void fixMoneyManagement(Element var0) throws JDOMException, IOException, BlockDefinitionException {
      ArrayList var1 = XMLUtil.getNestedElements(var0, "MoneyManagement");

      for (int var2 = 0; var2 < var1.size(); var2++) {
         Element var3 = (Element)var1.get(var2);
         if (var3.getChild("Method") == null) {
            Element var4 = new Element("Method");
            String var5 = var3.getAttributeValue("type");
            var4.setAttribute("type", var5 != null ? var5 : "MMNone");
            var4.setAttribute("use", "true");
            Element var6 = new Element("Params");
            Element var7 = var3.getChild("params");
            String var8 = "Param";
            if (var7 == null) {
               var7 = var3.getChild("Parameters");
               var8 = "Parameter";
            }

            if (var7 != null) {
               List var9 = var7.getChildren(var8);

               for (int var10 = 0; var10 < var9.size(); var10++) {
                  Element var11 = (Element)var9.get(var10);
                  var6.addContent(var11.clone().setName("Param"));
               }

               var3.removeContent(var7);
            }

            var4.addContent(var6);
            var3.addContent(var4);
         }
      }
   }

   private static void fixBlockAttributes(Element var0) throws BlockDefinitionException {
      List var1 = var0.getChildren();
      if (var1 != null) {
         for (int var2 = 0; var2 < var1.size(); var2++) {
            Element var3 = (Element)var1.get(var2);
            if (var3.getName().equals("Item")) {
               String var4 = var3.getAttributeValue("key");
               if (var4 != null) {
                  String var5 = blockCategoryTypes.get(var4);
                  if (var5 != null) {
                     var3.setAttribute("categoryType", var5);
                  }
               }
            }

            if (var3.getChildren() != null) {
               fixBlockAttributes(var3);
            }
         }
      }
   }

   public static void fixCategoryTypes(Element var0) throws JDOMException, IOException, BlockDefinitionException {
      fixBlockAttributes(var0);
      var0.setAttribute("Version", "3.9.133");
   }

   private static void loadCategoryTypesAndAttributes() throws Exception {
      synchronized (blockCategoryTypes) {
         if (blockCategoryTypes.size() <= 0) {
            itemAttributes = new HashMap<>();
            Element var1 = BlocksConfig.getConfigElement();
            ArrayList var2 = XMLUtil.getNestedElements(var1, "Item");

            for (int var3 = 0; var3 < var2.size(); var3++) {
               Element var4 = (Element)var2.get(var3);
               String var5 = var4.getAttributeValue("key");
               String var6 = var4.getAttributeValue("categoryType");
               if (var5 != null && var6 != null) {
                  blockCategoryTypes.put(var5, var6);
               }

               itemAttributes.put(var5, var4.getAttributes());
            }
         }
      }
   }

   public static void removeAllowRandom(Element var0) {
      Element var1 = var0.getChild("Strategy");
      if (var1 != null) {
         var1.removeAttribute("allowRandom");
      }
   }

   public static boolean isTemplate(Element var0) {
      List var1 = var0.getChildren();
      if (var1 != null && var1.size() > 0) {
         for (int var2 = 0; var2 < var1.size(); var2++) {
            Element var3 = (Element)var1.get(var2);
            if (var3.getName().equals("Item")) {
               String var4 = var3.getAttributeValue("key");
               if (var4 == null) {
                  continue;
               }

               if (var4.equals("OppositeValue")
                  || var4.equals("RandomValue")
                  || var4.equals("SameValue")
                  || var4.equals("RandomCondition")
                  || var4.equals("NegatedCondition")
                  || var4.equals("SameCondition")
                  || var4.equals("RandomAction")
                  || var4.equals("SameAction")
                  || var4.equals("OppositeAction")) {
                  return true;
               }

               List var5 = var3.getChildren("Param");
               if (var5 != null && var5.size() > 0) {
                  for (int var6 = 0; var6 < var5.size(); var6++) {
                     Element var7 = (Element)var5.get(var6);
                     String var8 = var7.getAttributeValue("generate");
                     if (var8 != null) {
                        String var9 = var7.getAttributeValue("key");
                        if (var9 == null || !var9.equals("#ReplaceExisting#")) {
                           return true;
                        }
                     }
                  }
               }
            }

            if (isTemplate(var3)) {
               return true;
            }
         }
      }

      return false;
   }

   private static void fixShifts(Element var0) {
      String[] var1 = new String[]{
         "BBBarClosesAboveDown",
         "BBBarClosesAboveUp",
         "BBBarClosesBelowDown",
         "BBBarClosesBelowUp",
         "BBBarOpensAboveDown",
         "BBBarOpensAboveDownAfterOpenBelow",
         "BBBarOpensAboveUp",
         "BBBarOpensAboveUpAfterOpenBelow",
         "BBBarOpensBelowDown",
         "BBBarOpensBelowDownAfterOpenAbove",
         "BBBarOpensBelowUp",
         "BBBarOpensBelowUpAfterOpenAbove",
         "BarOpensAboveHighestAfterOpenBelow",
         "BarOpensAboveLowestAfterOpenBelow",
         "BarOpensBelowHighestAfterOpenAbove",
         "BarOpensBelowLowestAfterOpenAbove",
         "KCBarClosesAboveLower",
         "KCBarClosesAboveUpper",
         "KCBarClosesBelowLower",
         "KCBarClosesBelowUpper",
         "KCBarOpensAboveLower",
         "KCBarOpensAboveLowerAfterOpenBelow",
         "KCBarOpensAboveUpper",
         "KCBarOpensAboveUpperAfterOpenBelow",
         "KCBarOpensBelowLower",
         "KCBarOpensBelowLowerAfterOpenAbove",
         "KCBarOpensBelowUpper",
         "KCBarOpensBelowUpperAfterOpenAbove",
         "LinRegBarClosesAbove",
         "LinRegBarClosesBelow",
         "LinRegBarOpensAbove",
         "LinRegBarOpensAboveAfterOpenBelow",
         "LinRegBarOpensBelow",
         "LinRegBarOpensBelowAfterOpenAbove",
         "MABarClosesAbove",
         "MABarClosesBelow",
         "MABarOpensAbove",
         "MABarOpensAboveAfterOpenBelow",
         "MABarOpensBelow",
         "MABarOpensBelowAfterOpenAbove"
      };
      List var2 = Arrays.asList(var1);
      ArrayList var3 = XMLUtil.getNestedElements(var0, "Item");

      for (int var4 = 0; var4 < var3.size(); var4++) {
         Element var5 = (Element)var3.get(var4);
         String var6 = var5.getAttributeValue("key");
         if (var6 != null && var2.contains(var6)) {
            List var7 = var5.getChildren("Param");
            if (var7 != null && var7.size() > 0) {
               boolean var8 = false;

               for (int var9 = 0; var9 < var7.size(); var9++) {
                  Element var10 = (Element)var7.get(var9);
                  String var11 = var10.getAttributeValue("key");
                  if (var11.equals("#Shift#")) {
                     var10.setText(var6.contains("Closes") ? "1" : "0");
                     var8 = true;
                     break;
                  }
               }

               if (!var8) {
                  Element var12 = new Element("Param");
                  var12.setAttribute("key", "#Shift#");
                  var12.setAttribute("controlType", "jspinnerVar");
                  var12.setAttribute("type", "int");
                  var12.setText(var6.contains("Closes") ? "1" : "0");
                  var5.addContent(var12);
               }
            }
         }
      }
   }
}
