/*
 * Decompiled with CFR 0.152.
 */
package com.strategyquant.lib.app;

public class AppSettingsConst {
    public static final String TRADE_LIST_VIEW = "tradelistView";
    public static final String RT_VIEW = "rtView";
    public static final String RT_RR_VIEW = "rtRRView";
    public static final String APP_PATH = "appPath";
    public static final String PROJECTS_PATH = "projectsPath";
    public static final String BB_TEMPLATES_PATH = "templatesPath";
    public static final String IMPORT_PATH = "importPath";
    public static final String USER_PATH = "userPath";
    public static final String SETTINGS_PATH = "settingsPath";
    public static final String TESTS_PATH = "testsPath";
    public static final String STRATEGY_TEMPLATES_PATH = "strategyTemplatesPath";
    public static final String STRATEGIES_PATH = "strategiesPath";
    public static final String BUILD_CONFIG_PATH = "configsPath";
    public static final String BUILD_TEMPLATES_PATH = "buildTemplatesPath";
    public static final String LAST_FOLDER_USED = "lastFolderUsed";
    public static final String SMTPServer = "SMTPServer";
    public static final String SMTPPort = "SMTPPort";
    public static final String SMTPUsername = "SMTPUsername";
    public static final String SMTPPassword = "SMTPPassword";
    public static final String SMTPEmailFrom = "SMTPEmailFrom";
    public static final String SMTPUseSSL = "SMTPUseSSL";
    public static final String SourceCodeType = "sourceCodeType";
    public static final String SourceCodeVariables = "sourceCodeVariables";
    public static final String SourceCodeSymmetry = "sourceCodeSymmetry";
    public static final String SourceCodePeriodParams = "sourceCodePeriodParams";
    public static final String SourceCodeShiftParams = "sourceCodeShiftParams";
    public static final String SourceCodeExitParamsUsed = "sourceCodeExitParamsUsed";
    public static final String SourceCodeExitParamsUnused = "sourceCodeExitParamsUnused";
    public static final String SourceCodeConstantsParams = "sourceCodeConstantsParams";
    public static final String SourceCodeOtherParams = "sourceCodeOtherParams";
    public static final String SourceCodeRecommendedParams = "sourceCodeRecommendedParams";
    public static final String sourceCodeBooleanParamsUnused = "sourceCodeBooleanParamsUnused";
    public static final String SoundsOff = "globalSoundsOff";
    public static final String UseAdvancedFileChooser = "useAdvancedFileChooser";
    public static final String ShowControlOrders = "showControlOrders";
    public static final String HeaderCustomText = "headerCustomText";
    public static final String FooterCustomText = "footerCustomText";
    public static final String AutoUpdate = "autoUpdate";
    public static final String DefaultResultToDisplay = "defaultResultToDisplay";
    public static final String DebugLevelActive = "debugLevelActive";
    public static final String Timezone = "timezone";
    public static final String EngineDeleteLogOnStart = "engineDeleteLogOnStart";
    public static final String GpuAccelerated = "gpuAccelerated";
    public static final String OffScreenRenderingEnabled = "offScreenRenderingEnabled";
    public static final String ThreadAffinity = "threadAffinity";
    public static final String DontStorePendingOrders = "dontStorePendingOrders";
    public static final String DontStoreOP3DChartsData = "dontStoreOP3DChartsData";
    public static final String CoreUsage = "coreUsage";
    public static final String HighPriority = "highPriority";
    public static final String MemoryProtection = "memoryProtection";
    public static final String StoreChartData = "storeChartData";
    public static final String DatabankSyncInterval = "databankSyncType";
    public static final String SyncDatabanksAfterTaskDone = "syncDatabanksAfterTaskDone";
    public static final String MemoryCleanup = "memoryCleanup";
    public static final String MemoryCleanupInterval = "memoryCleanupInterval";
    public static final String GCType = "GCType";
    public static final String ParallelDownload = "parallelDownload";
    public static final String CdnParallelDownload = "cdnParallelDownload";
    public static final String CdnPreferred = "cdnPreferred";
    public static final String WebServerPort = "WebServerPort";
    public static final String WebServerPortUsed = "WebServerPortUsed";
    public static final String BrowserToken = "BrowserToken";
    public static final String ComputePipsMetrics = "ComputePipsMetrics";
    public static final String ComputePctsMetrics = "ComputePctsMetrics";
    public static final String ComputeSeparateMetrics = "ComputeSeparateMetrics";
    public static final String AWEditorVersion = "AWEditorVersion";
    public static final String USER_EXTEND_ALT_DIR = "userExtendAltDir";
    public static final String SKIN = "skin";
    public static final String LANGUAGE = "language";
    public static final String OptProfileView = "optProfileView";
    public static final String SSL_USE = "SSLUse";
    public static final String SSL_KEYSTORE_PATH = "SSLKeystorePath";
    public static final String SSL_KEYSTORE_PASS = "SSLKeystorePass";
}

