package SQ.Internal;

import java.lang.annotation.Annotation;
import java.lang.reflect.Field;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Iterator;
import java.util.List;

import com.strategyquant.tradinglib.*;
import com.strategyquant.tradinglib.blocks.ParameterAnnotationGenerator;
import org.apache.commons.lang3.StringUtils;
import org.jdom2.Element;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import com.strategyquant.lib.SQUtils;
import com.strategyquant.lib.ValuesMap;
import com.strategyquant.lib.XMLUtil;
import com.strategyquant.tradinglib.blocks.annotations.Value;
import com.strategyquant.tradinglib.generator.StrategyStandardTemplateSQ4;
import com.strategyquant.tradinglib.options.TradingOptions;
import com.strategyquant.tradinglib.options.TradingOptionsList;
import com.strategyquant.tradinglib.project.ProjectConfigHelper;
import com.strategyquant.tradinglib.propertygrid.IPGParameter;

/**
 * The Class VariablesTransformer.
 */
public class VariablesTransformer {

	/** The Constant Log. */
	private static final Logger Log = LoggerFactory.getLogger(VariablesTransformer.class);

	/** The Constant ParamTypeLine. */
	public static final String ParamTypeLine = "ParamTypeLine";

	/** The Constant generatedAttrName. */
	private static final String generatedAttrName = "autoGenerated";

	/** The Constant makeExternalAttrName. */
	private static final String makeExternalAttrName = "makeExternal";

	/** The Constant ParamTypeUnknown. */
	private static final String ParamTypeUnknown = null;
	//private static final ValuesMap allParams = new ValuesMap();

	/** The strategy. */
	private XmlStrategy strategy;

	/** The symmetry enabled. */
	private boolean symmetryEnabled;

	/** The min period. */
	private String minPeriod;

	/** The min shift. */
	private String minShift;

	/**
	 * The Enum RuleType.
	 */
	private static enum RuleType {
		/** The long. */
		LONG,
		/** The short. */
		SHORT,
		/** The unknown. */
		UNKNOWN,
		/** The trading signals. */
		TRADING_SIGNALS,

		EXPLORE
	}

	//------------------------------------------------------------------------
	//------------------------------------------------------------------------
	//------------------------------------------------------------------------

	/**
	 * Instantiates a new variables transformer.
	 *
	 * @param strategy the strategy
	 */
	public VariablesTransformer(XmlStrategy strategy){
		this.strategy = strategy;
		this.symmetryEnabled = checkSymmetryEnabled();

		this.minPeriod = SQUtils.doubleToString(Value.MinPeriod);
		this.minShift = SQUtils.doubleToString(Value.MinShift);

		/**
		 allParams.set(ParametrizationTypes.ParamTypeRecommended, false);
		 allParams.set(ParametrizationTypes.ParamTypeBoolean, true);
		 allParams.set(ParametrizationTypes.ParamTypeConstant, true);
		 allParams.set(ParametrizationTypes.ParamTypeEntryLevel, true);
		 allParams.set(ParametrizationTypes.ParamTypeEntryLogic, false);
		 allParams.set(ParametrizationTypes.ParamTypeExitUnused, true);
		 allParams.set(ParametrizationTypes.ParamTypeExitUsed, true);
		 allParams.set(ParametrizationTypes.ParamTypeOtherParam, true);
		 allParams.set(ParametrizationTypes.ParamTypePeriod, true);
		 allParams.set(ParametrizationTypes.ParamTypeShift, true);
		 allParams.set(ParametrizationTypes.ParamTypeTradingOptions, true);
		 */
	}

	//------------------------------------------------------------------------

	/**
	 * Check symmetry enabled.
	 *
	 * @return true, if successful
	 */
	private boolean checkSymmetryEnabled(){
		if(true) return true; // it seems we don't need to recognize it at all, it seems to be working also for unknown rules - https://roadmap.strategyquant.com/tasks/sq4_011163

		ArrayList<Element> ruleElems = XMLUtil.getNestedElements(strategy.getStrategyXml(), "Rule");

		//replace all param values with variables
		for(int i=0; i<ruleElems.size(); i++) {
			Element ruleElem = ruleElems.get(i);

			try {
				if(getRuleType(ruleElem).equals(RuleType.UNKNOWN)){
					return false;
				}
			} catch (Exception e){
				return false;
			}
		}

		return true;
	}

	//------------------------------------------------------------------------

	/**
	 * Transform to variables.
	 *
	 * @param symmetry the symmetry
	 * @param parameterTypes the parameter types
	 * @throws Exception the exception
	 */
	public void transformToVariables(boolean symmetry, ValuesMap parameterTypes) throws Exception{
		if(isTransformed()) backToNumbers();

		boolean hasRecommended;

		if(parameterTypes == null){
			// we'l keep it null, it will mean all parameters
			//parameterTypes = allParams;

			hasRecommended = false;
		} else {

			if(recognizeEmpty(parameterTypes)) {
				return;
			}

			hasRecommended = parameterTypes.getBoolean(ParametrizationTypes.ParamTypeRecommended, false);
			if(hasRecommended) {
				symmetry = true;
			}
		}

		Element strategyXML = strategy.getStrategyXml();

		ArrayList<Element> ruleElems = XMLUtil.getNestedElements(strategyXML, "Rule");

		String paramType;

		// replace all param values with variables
		for(int i=0; i<ruleElems.size(); i++) {
			Element ruleElem = ruleElems.get(i);
			RuleType ruleType = getRuleType(ruleElem);

			ArrayList<Element> items = findItems(ruleElem);

			for(int j=0; j<items.size(); j++) {
				Element itemElem = items.get(j);
				String itemKey = itemElem.getAttributeValue("key");

				List<Element> children = itemElem.getChildren("Param");

				for(int k=0; k<children.size(); k++) {
					Element paramElem = children.get(k);

					String paramKey = getParamKey(paramElem, itemKey);
					if(paramKey == null) continue;

					String isVariable = paramElem.getAttributeValue("variable");
					if(isVariable != null && isVariable.equals("true")) {
						// it already is variable
						String varRef = paramElem.getTextTrim();
						Variable existingVar = strategy.variables().get(varRef);
						if(existingVar == null && strategy.variables().getById(varRef) == null) {
							if(paramKey.equals("#Shift#") || paramKey.equals("#Type#")) {
								String defaultValue = paramElem.getAttributeValue("defaultValue");
								if(defaultValue != null) {
									paramElem.setText(defaultValue);
								} else {
									paramElem.setText("0");
								}
								paramElem.setAttribute("variable", "false");
								// fall through to normal processing
							} else {
								fixMinMaxVariable(paramElem);
								continue;
							}
						} else {
							fixMinMaxVariable(paramElem);
							continue;
						}
					}

					if(paramElem.getChildren().size() > 0) {
						ArrayList<Element> nestedElems = XMLUtil.getNestedElements(paramElem, "Param");

						for(int l=0; l<nestedElems.size(); l++) {
							Element nestedParam = nestedElems.get(l);

							boolean isExitParam = false;

							String formulaParentKey = getFormulaParentKey(nestedParam);
							if(formulaParentKey == null) {
								isExitParam = true;
							} else {
								if(formulaParentKey.contains(".PctValue") || formulaParentKey.contains(".FixedValue") || formulaParentKey.contains(".ATRBasedValue")) {
									isExitParam = true;
								}
							}

							if(isExitParam) {
								String nestedParamKey = getParamKey(nestedParam, itemKey);
								if(nestedParamKey != null){

									if(nestedParamKey.equals("#Value#")) {
										Element elParent = nestedParam.getParentElement();
										if(elParent.getAttributeValue("key").contains("ATR")) {
											nestedParamKey = "Coef";
										} else {
											nestedParamKey = "";
										}
									}


									if(nestedParamKey.equals("#AtrPeriod#")) {
										paramType = ParametrizationTypes.ParamTypeOtherParam;
									}
									else {
										paramType = getParameterType(paramElem, ruleType, itemKey, paramKey, true, formulaParentKey, nestedParamKey);
									}

									//we first check if the param value isn't a XML predefined variable. There may be some missing attributes
									if(!tryFixVariableAttributes(nestedParam, paramType)) {
										//if not, we process it further
										if(paramTypeToTransform(paramType, parameterTypes, hasRecommended)) {
											addVariable(nestedParam, symmetry, ruleType, itemKey, paramKey + nestedParamKey, paramType);
										}
									}
								}

							} else if(formulaParentKey.equals("SQ.Formulas.Price.UseFormula")) {
								// entry price
								String nestedParamKey = getParamKey(nestedParam, itemKey);
								if(nestedParamKey != null){
									paramType = getParameterType(paramElem, ruleType, itemKey, paramKey, true, formulaParentKey, nestedParamKey);

									//we first check if the param value isn't a XML predefined variable. There may be some missing attributes
									if(!tryFixVariableAttributes(nestedParam, paramType)) {
										//if not, we process it further
										if(paramTypeToTransform(paramType, parameterTypes, hasRecommended)) {
											if(paramType != ParametrizationTypes.ParamTypePeriod || checkEntryLevels(paramElem, parameterTypes)) {
												addVariable(nestedParam, symmetry, ruleType, itemKey, paramKey + "EntryMult", paramType);
											}
										}
									}
								}
							}
						}
					}
					else {
						paramType = getParameterType(paramElem, ruleType, itemKey, paramKey, false, null, null);

						//we first check if the param value isn't a XML predefined variable. There may be some missing attributes
						if(!tryFixVariableAttributes(paramElem, paramType)) {
							//if not, we process it further
							if(paramTypeToTransform(paramType, parameterTypes, hasRecommended)) {
								if(paramType != ParametrizationTypes.ParamTypePeriod || checkEntryLevels(paramElem, parameterTypes)) {
									addVariable(paramElem, symmetry, ruleType, itemKey, paramKey, paramType);
								}
							}
						}
					}
				}
			}
		}

		//for(Variable var : strategy.variables()) {
		//	Log.info("VAR: "+var.getName()+" type: "+ var.getType());
		//}

		//Load Trading Options variables

		if(parameterTypes == null || parameterTypes.getBoolean(ParametrizationTypes.ParamTypeTradingOptions, false)) {
			try {
				List<TradingOption> tradingOptions = TradingOptionsList.getInstance().getAvailableClasses();
				HashMap<String, TradingOption> strategyTradingOptions = null;

				Element elTradingOptions = strategyXML.getChild("TradingOptions");

				try {
					if(elTradingOptions != null) {
						TradingOptions options = ProjectConfigHelper.getOptions(elTradingOptions);

						strategyTradingOptions = new HashMap<>();

						for(int a=0; a<options.size(); a++) {
							TradingOption option = options.get(a);
							strategyTradingOptions.put(option.getClass().getSimpleName(), option);
						}
					}
				}
				catch(Exception e) {
					Log.error("Cannot load strategy trading options", e);
				}

				for(int a=0; a<tradingOptions.size(); a++) {
					TradingOption option = tradingOptions.get(a);
					String optionClass = option.getClass().getSimpleName();

					if(optionClass.equals("SessionOption") || optionClass.equals("StoreChartData") || optionClass.equals("ComputeDailyStats")) continue;

					ArrayList<IPGParameter> optionParams = option.getParams();

					TradingOption strategyOption = null;

					if(strategyTradingOptions != null && strategyTradingOptions.containsKey(optionClass)) {
						strategyOption = strategyTradingOptions.get(optionClass);
					}

					for(int i=0; i<optionParams.size(); i++) {
						IPGParameter param = optionParams.get(i);
						String paramKey = param.getKey();
						String variableKey = optionClass + "." + paramKey;
						String variableName = param.getName();
						String variableDataType = "string";

						String paramValue = null;
						if(strategyOption != null) {
							try {
								paramValue = String.valueOf(strategyOption.getParameterValue(paramKey));
							} catch(Exception e) {
								Log.error("Cannot set variable '" + variableKey + "'", e);
							}
						}

						try {
							Field paramField = option.getClass().getField(paramKey);
							String paramClass = paramField.getType().getSimpleName();
							Editor editorAnnotation = paramField.getAnnotation(Editor.class);
							Parameter parameterAnnotation = paramField.getAnnotation(Parameter.class);

							if(editorAnnotation != null && editorAnnotation.type() == Editors.Time) {
								variableDataType = "time";
							}
							else if(paramClass.equals(Boolean.class.getSimpleName()) || paramClass.equals(boolean.class.getSimpleName())){
								variableDataType = "boolean";
							}
							else if(paramClass.equals(Integer.class.getSimpleName()) || paramClass.equals(int.class.getSimpleName())) {
								variableDataType = "int";
							}
							else if(paramClass.equals(Double.class.getSimpleName()) || paramClass.equals(double.class.getSimpleName())) {
								variableDataType = "double";
							}
							else if(paramClass.equals(String.class.getSimpleName())) {
								variableDataType = "string";
							}
							else {
								Log.error("Unexpected trading option param class '" + paramClass + "', param field '"+ paramField.getName()+"'.");
							}

							if(paramValue == null) {
								if(parameterAnnotation != null) {
									paramValue = parameterAnnotation.defaultValue();
								}
								else {
									paramValue = param.print();
								}
							}
						}
						catch(Exception e) {
							Log.error("Cannot load trading option variable " + variableKey, e);
						}

						Variable variable = new Variable(
								variableKey,
								variableName,
								variableDataType,
								paramValue,
								true,
								ParametrizationTypes.ParamTypeTradingOptions,
								false
						);
						strategy.variables().add(variable);
					}
				}
			}
			catch(Exception e) {
				Log.error("Cannot load trading options variables", e);
			}
		}

		generateVariablesXML();
	}

	//------------------------------------------------------------------------

	/**
	 * speciality for periods and entry levels - verifies if the period is not used in indicator in entry order.
	 * If yes, it checks, if Entry (levels) is selected.
	 * @param paramElem
	 * @param parameterTypes
	 * @return
	 */
	private boolean checkEntryLevels(Element paramElem, ValuesMap parameterTypes) {
		if(parameterTypes == null) {
			return true;
		}

		Element elCurrent = paramElem;
		boolean isEntry = false;

		while(true) {
			Element el = elCurrent.getParentElement();
			if(el == null) {
				break;
			}

			String key = el.getAttributeValue("key");
			if(key != null && (key.contains("EnterAt") ||key.contains("ReverseAt"))) {
				isEntry = true;
				break;
			}

			elCurrent = el;
		}

		if(!isEntry) {
			return true; // generate variable
		}

		if(parameterTypes.getBoolean(ParametrizationTypes.ParamTypeEntryLevel)) {
			return true;
		}

		return false;
	}

	//------------------------------------------------------------------------

	/**
	 * Recognize empty.
	 *
	 * @param parameterTypes the parameter types
	 * @return true, if successful
	 */
	private boolean recognizeEmpty(ValuesMap parameterTypes) {
		String[] keys = parameterTypes.getAllKeys();

		for(int i=0; i<keys.length; i++) {
			if(parameterTypes.getBoolean(keys[i], false)) {
				return false;
			}
		}

		return true;
	}

	//------------------------------------------------------------------------

	private boolean IsSignalVariable(String name){
		Variable existingVariable = strategy.variables().get(name);
		if(existingVariable != null){
			ArrayList<Element> signalElems = XMLUtil.getNestedElements(strategy.getStrategyXml(), "signal");
			for(int i=0; i<signalElems.size(); i++) {
				Element signalElem = signalElems.get(i);
				if(signalElem.getAttributeValue("variable").equals(existingVariable.getId())){
					return true;
				}
			}
		}
		return false;
	}
	/**
	 * Try fix variable attributes.
	 *
	 * @param paramElem the param elem
	 * @param paramType the param type
	 * @return true, if successful
	 */
	private boolean tryFixVariableAttributes(Element paramElem, String paramType){
		String value = paramElem.getText();
		String type = paramElem.getAttributeValue("type");

		if(value != null) {
			if(paramElem.getAttributeValue("variable") == null) {
				Variable existingVariable = strategy.variables().get(value);
				if (existingVariable != null) {
					if (!IsSignalVariable(value)) {
						// If signal variable marked as variable (true), the monte carlo tests wouldn't run
						paramElem.setAttribute("variable", "true");
					}

					if (type != null) {
						paramElem.setAttribute("variableType", type.toUpperCase());
					}
					existingVariable.setParamType(paramType);
					return true;
				}
			} else {
				// it already is variable. Check if it exists
				Variable existingVariable = strategy.variables().get(value);
				if (existingVariable != null) {
					return true; // don't create new variable
				}
			}
		}

		return false;
	}

	//------------------------------------------------------------------------

	/**
	 * Fix min max variable.
	 *
	 * @param paramElem the param elem
	 */
	private void fixMinMaxVariable(Element paramElem) {
		String variableId = paramElem.getText();
		if(variableId== null) {
			return;
		}

		Variable var = strategy.variables().getById(variableId);
		if(var == null) {
			return;
		}

		// try to set variable min and max using element parameters
		double min = Integer.MAX_VALUE;
		double max = -Integer.MAX_VALUE;

		String controlType = paramElem.getAttributeValue("controlType");
		if(controlType == null) {
			return;
		}

		if(controlType.contains("jspinner")) {
			// to do later

		}
		else if(controlType.contains("combo")) {
			String values = paramElem.getAttributeValue("values");
			if(values == null) {
				return;
			}

			String[] vals = values.split(",");
			if(vals == null || vals.length == 0)  {
				return;
			}

			for(int i=0; i<vals.length; i++) {
				String[] vals2 = vals[i].split("=");

				if(vals2 == null || vals2.length != 2) {
					continue;
				}

				double doubleVal = Double.parseDouble(vals2[1]);

				if(doubleVal < min) {
					min = doubleVal;
				}
				if(doubleVal > max) {
					max = doubleVal;
				}
			}
		}

		// nevim, proc nasledujici radek byl zakomentovan, musi tady byt
		if(min == Integer.MAX_VALUE && max == -Integer.MAX_VALUE) return;

		var.setMinMax(min, max);
	}

	//------------------------------------------------------------------------

	/**
	 * Gets the formula parent key.
	 *
	 * @param el the el
	 * @return the formula parent key
	 */
	private String getFormulaParentKey(Element el) {

		for(int i=0; i<50; i++) {
			Element elParent = el.getParentElement();

			if(elParent == null) {
				return null;
			}

			if(elParent.getName().equals("Formula")) {
				return elParent.getAttributeValue("key");
			}

			el = elParent;
		}

		return null;
	}

	//------------------------------------------------------------------------

	/**
	 * Param type to transform.
	 *
	 * @param paramType the param type
	 * @param parameterTypes the parameter types
	 * @param hasRecommended the has recommended
	 * @return true, if successful
	 */
	private boolean paramTypeToTransform(String paramType, ValuesMap parameterTypes, boolean hasRecommended) {
		if(paramType == null) {
			return false;
		}

		if(hasRecommended) {
			if(paramType.equals(ParametrizationTypes.ParamTypePeriod) || paramType.equals(ParametrizationTypes.ParamTypeEntryLevel) || paramType.equals(ParametrizationTypes.ParamTypeExitUsed)) {
				return true;
			}
		}

		if(parameterTypes == null) {
			return true;
		}

		return parameterTypes.getBoolean(paramType, false);
	}

	//------------------------------------------------------------------------

	/**
	 * Gets the parameter type.
	 *
	 * @param paramElem the param elem
	 * @param ruleType the rule type
	 * @param itemKey the item key
	 * @param paramKey the param key
	 * @param isNested the is nested
	 * @param formulaParentKey the formula parent key
	 * @param nestedParamKey the nested param key
	 * @return the parameter type
	 */
	private String getParameterType(Element paramElem, RuleType ruleType, String itemKey, String paramKey, boolean isNested, String formulaParentKey, String nestedParamKey) {
		if(paramKey.contains("#BarsValid#") || paramKey.contains("#ReplaceExisting#")) {
			return ParametrizationTypes.ParamTypeEntryLogic;
		}

		String paramType = paramElem.getAttributeValue("type");
		if(paramType != null && paramType.equals("boolean")){
			return ParametrizationTypes.ParamTypeBoolean;
		}

		if(paramKey.contains("Period#") || paramKey.startsWith("#Fast") || paramKey.startsWith("#Slow") || paramKey.startsWith("#Smooth") || paramKey.contains("#Period")) {
			return ParametrizationTypes.ParamTypePeriod;
		}

		if(paramKey.equals("#Shift#")) {
			return ParametrizationTypes.ParamTypeShift;
		}

		if(paramKey.equals("#Line#")) {
			return ParamTypeLine;
		}

		if(paramKey.equals("#Value#")) {
			String controlType = paramElem.getAttributeValue("controlType");
			if(controlType != null && controlType.equals("combo")) {
				return ParamTypeLine;
			}
		}

		String genMinValue = paramElem.getAttributeValue("genMinValue");
		if(genMinValue != null) {
			if(genMinValue.equals(minPeriod)) {
				return ParametrizationTypes.ParamTypePeriod;
			}

			if(genMinValue.equals(minShift)) {
				return ParametrizationTypes.ParamTypeShift;
			}
		}

		if(itemKey.equals("Number") || paramKey.equals("#Level#")) {
			return ParametrizationTypes.ParamTypeConstant;
		}

		if(!isNested) {
			if(itemKey.startsWith("EnterAt") || itemKey.startsWith("EnterReverseAt")) {
				if(paramKey.equals("#ExitAfterBars.ExitAfterBars#")) {
					String value = paramElem.getText();

					if(value.equals("0")) {
						return ParametrizationTypes.ParamTypeExitUnused;
					}
				}

				if(isUsed(paramElem)) {
					return ParametrizationTypes.ParamTypeExitUsed;
				} else {
					return ParametrizationTypes.ParamTypeExitUnused;
				}
			}

			if(paramType.equals("int")) {
				// it can still be a period param
				if(tryRecognizePeriodParam(itemKey, paramKey)) {
					return ParametrizationTypes.ParamTypePeriod;
				}
			}

			return ParametrizationTypes.ParamTypeOtherParam;
		}

		if(isNested) {
			// it must be parameter in Entry Order
			if(formulaParentKey != null && formulaParentKey.equals("SQ.Formulas.Price.UseFormula")) {
				// it is part of entry
				if(nestedParamKey != null && (nestedParamKey.equals("#Number#"))) {
					if(itemKey.equals("AssignVariable")) {
						return ParamTypeUnknown;
					}
					return ParametrizationTypes.ParamTypeEntryLevel;
				} else {
					return ParamTypeUnknown;
				}
			}
			if(isUsed(paramElem)) {
				return ParametrizationTypes.ParamTypeExitUsed;
			} else {
				return ParametrizationTypes.ParamTypeExitUnused;
			}

		}

		return ParamTypeUnknown;
	}

	//------------------------------------------------------------------------

	private boolean tryRecognizePeriodParam(String itemKey, String paramKey) {
		try {
			IBlock block = Blocks.get(itemKey);
			Class<?> aClass = block.getClass();

			paramKey = paramKey.replace("#", "");

			Field[] fields = aClass.getFields();
			for(int i=0; i<fields.length; i++) {
				Field field = fields[i];

				if(field.getName().equals(paramKey)) {
					for(Annotation annotation : field.getAnnotations()) {
						if(annotation instanceof Parameter) {
							if(((Parameter) annotation).isPeriod()) {
								return true;
							}
						}
					}
				}
			}

		} catch(Exception e) {
			if(e.getMessage().contains("talib_")) {
				Log.debug("Error recognizing parameter type from class: " + e.getMessage());
			} else {
				Log.error("Error recognizing parameter type from class: " + e.getMessage());
			}
		}

		return false;
	}

	//------------------------------------------------------------------------

	/**
	 * Checks if is used.
	 *
	 * @param paramElem the param elem
	 * @return true, if is used
	 */
	private boolean isUsed(Element paramElem) {
		String isFormula = paramElem.getAttributeValue("isFormula");
		if(isFormula != null && isFormula.equals("true")) {
			Element elFormula = paramElem.getChild("Formula");
			String key = elFormula.getAttributeValue("key");

			if(key.endsWith(".None")) {
				return false;
			} else {
				return true;
			}
		}

		// it is normal parameter
		String defaultValue = paramElem.getAttributeValue("defaultValue");
		if(defaultValue == null) {
			return true;
		}

		String value = paramElem.getValue();
		if(value == null) {
			return true;
		}

		if(defaultValue.equals(value)) {
			// if value = default value hen the parameter is considered to be not used
			return false;
		}

		return true;
	}

	//------------------------------------------------------------------------

	/**
	 * Back to numbers.
	 *
	 * @throws Exception the exception
	 */
	public void backToNumbers() throws Exception{
		if(!isTransformed()) return;

		ArrayList<Element> ruleElems = XMLUtil.getNestedElements(strategy.getStrategyXml(), "Rule");

		//replace all param values with variables
		for(int i=0; i<ruleElems.size(); i++) {
			Element ruleElem = ruleElems.get(i);

			ArrayList<Element> items = findItems(ruleElem);

			for(int j=0; j<items.size(); j++) {
				Element itemElem = items.get(j);
				String itemKey = itemElem.getAttributeValue("key");

				List<Element> children = itemElem.getChildren("Param");
				for(int k=0; k<children.size(); k++) {
					Element paramElem = children.get(k);

					String paramKey = getParamKey(paramElem, itemKey);
					if(paramKey == null) continue;

					if(paramElem.getChildren().size() > 0){
						ArrayList<Element> nestedElems = XMLUtil.getNestedElements(paramElem, "Param");

						for(int l=0; l<nestedElems.size(); l++) {
							Element nestedParam = nestedElems.get(l);

							String nestedParamKey = getParamKey(nestedParam, itemKey);
							if(nestedParamKey != null){
								replaceVariableWithNumber(nestedParam);
							}
						}
					}
					else {
						replaceVariableWithNumber(paramElem);
					}
				}
			}
		}

		removeGeneratedVariables();
	}

	//------------------------------------------------------------------------

	/**
	 * Adds the variable.
	 *
	 * @param paramElem the param elem
	 * @param symmetry the symmetry
	 * @param ruleType the rule type
	 * @param itemKey the item key
	 * @param paramKey the param key
	 * @param paramType the param type
	 */
	private String addVariable(Element paramElem, boolean symmetry, RuleType ruleType, String itemKey, String paramKey, String paramType){
		String type = paramElem.getAttributeValue("type");
		if(type == null) {
			if(paramElem.getAttributeValue("key").equals("#Number#")) {
				type = "double";
			} else {
				return null;
			}
		}

		// toto prida HighestInRange.TimeFrom/To parameters, ale su typu string, nie time.
		// mli by sa aj v snippetoch prerobit na typ int, potom by mali fungovat
		//if(!paramKey.equals("#TimeFrom#") && !paramKey.equals("#TimeTo#")) {
		if(type.equals("data") || type.equals("string")) {
			// skip variables for chart
			return null;
		}
		//}

		if(paramKey.contains("Direction") || paramKey.equals("#MagicNumber#")) {
			// skip variables for these params
			return null;
		}

		paramKey = SQUtils.renameActionParams(paramKey);
		paramKey = paramKey.replace("#", "");

		paramElem.setAttribute("variable", "true");

		String value = paramElem.getTextTrim();

		if(strategy.variables().getById(value) != null) {
			//it's not a simple value, but already defined variable
			return null;
		}

		if(value.endsWith(".00")) {
			value = value.substring(0, value.length()-3);
		}

		if(value.contains(".")) {
			while(value.endsWith("0")) {
				value = value.substring(0, value.length()-1);
			}
		}

		if(value.endsWith(".")) {
			value = value.substring(0, value.length()-1);
		}

		String variableName = generateVariableName(paramElem, symmetry, ruleType, itemKey, paramKey, value);

		if(strategy.variables().get(variableName) == null){
			Variable variable = new Variable(
					variableName,
					variableName,
					type,
					value,
					true,
					paramType,
					false
			);
			strategy.variables().add(variable);

			paramElem.setText(variableName);
		}
		else {
			paramElem.setText(strategy.variables().get(variableName).getId());
		}

		return variableName;
	}

	//------------------------------------------------------------------------

	/**
	 * Generate variable name.
	 *
	 * @param paramElem the param elem
	 * @param symmetry the symmetry
	 * @param ruleType the rule type
	 * @param itemKey the item key
	 * @param paramKey the param key
	 * @param value the value
	 * @return the string
	 */
	private String generateVariableName(Element paramElem, boolean symmetry, RuleType ruleType, String itemKey, String paramKey, String value) {
		if(ruleType.equals(RuleType.UNKNOWN)) {
			symmetry = true;
		}

		String name = "";
		String newItemKey = null;

		if(symmetry) {
			String oppositeItemKey = Blocks.getOppositeBlockKey(itemKey);
			if(!oppositeItemKey.equals(itemKey)) {
				// blocks have different names, for example DEMChangesUp / DEMChangesDown
				// remove the difference and create only DEMChanges
				newItemKey = findSameString(itemKey, oppositeItemKey);
			}

		} else {
			if(ruleType.equals(RuleType.TRADING_SIGNALS)) {
				ruleType = recognizeRuleTypeFromElement(paramElem, ruleType);
			}

			name = (ruleType.equals(RuleType.LONG) ? "Long" : "Short");
		}

		if(itemKey.contains("EnterAt")) {
			itemKey = "";
		}

		if(itemKey.equals(paramKey)) {
			name += (newItemKey != null ? newItemKey : itemKey);
		} else {
			name += (newItemKey != null ? newItemKey : itemKey) + paramKey;
		}

		String parts[] = paramKey.split("\\.");

		if(parts.length == 2) {
			if(parts[0].equals(parts[1])) {
				paramKey = parts[0];

			} else if(parts[1].contains(parts[0])) {
				paramKey = parts[1].replace(parts[0], "");
			}
		}

		int index = 1;
		String finalName = shortenName(name + index);

		Variable variable = strategy.variables().get(finalName);

		while(variable != null && !variable.getValue().equals(value)){
			index++;
			finalName = shortenName(name + index);
			variable = strategy.variables().get(finalName);
		}

		finalName = finalName.replace(".", "_");

		return finalName;
	}

	//------------------------------------------------------------------------

	/**
	 * Recognize rule type from element.
	 *
	 * @param paramElem the param elem
	 * @param ruleType the rule type
	 * @return the rule type
	 */
	private RuleType recognizeRuleTypeFromElement(Element paramElem, RuleType ruleType) {
		Element elSignal = XMLUtil.findFirstParent(paramElem, "signal");
		if(elSignal == null) {
			return ruleType;
		}

		String varId = elSignal.getAttributeValue("variable");
		if(varId == null) {
			return ruleType;
		}

		switch(varId) {
			case StrategyStandardTemplateSQ4.SGN_LONG_ENTRY_ID: return RuleType.LONG;
			case StrategyStandardTemplateSQ4.SGN_LONG_EXIT_ID: return RuleType.LONG;
			case StrategyStandardTemplateSQ4.SGN_SHORT_ENTRY_ID: return RuleType.SHORT;
			case StrategyStandardTemplateSQ4.SGN_SHORT_EXIT_ID: return RuleType.SHORT;
		}

		return ruleType;
	}

	//------------------------------------------------------------------------

	/**
	 * Find same string.
	 *
	 * @param s1 the s 1
	 * @param s2 the s 2
	 * @return the string
	 */
	private String findSameString(String s1, String s2) {
		StringBuilder sb1 = new StringBuilder();

		char c;
		for(int i=0; i<Math.min(s1.length(),s2.length()); i++){
			if((c = s1.charAt(i)) == s2.charAt(i)){
				sb1.append(c);
			}
		}
		return sb1.toString();
	}

	//------------------------------------------------------------------------

	/**
	 * Shorten name.
	 *
	 * @param name the name
	 * @return the string
	 */
	private String shortenName(String name){
		if(name.length() <= 20) return name;

		String[] words = StringUtils.splitByCharacterTypeCamelCase(name);

		for(int i=words.length-1; i>0; i--) {
			words[i] = SQUtils.shortenWord(words[i], 3);

			if(checkWordsSize(words) <= 20) {
				break;
			}
		}

		StringBuilder shortName = new StringBuilder();
		for(int i=0; i<words.length; i++) {
			shortName.append(words[i]);
		}

		return shortName.toString();
	}

	//------------------------------------------------------------------------

	/**
	 * Check words size.
	 *
	 * @param words the words
	 * @return the int
	 */
	private int checkWordsSize(String[] words) {
		int length = 0;
		for(int i=0; i<words.length; i++) {
			length += words[i].length();
		}

		return length;
	}

	//------------------------------------------------------------------------

	/**
	 * Generate variables XML.
	 *
	 * @throws Exception the exception
	 */
	private void generateVariablesXML() throws Exception{
		Element variablesElem = getChildElem(getChildElem(strategy.getStrategyXml(), "Strategy"), "Variables");

		variablesElem.removeContent();
		Variables vars = strategy.variables();

		for(int i=0; i<vars.size(); i++) {
			Variable variable = vars.get(i);

			Element variableElem = variable.getXML().detach();

			if(variable.isAutoGenerated()){
				variableElem.setAttribute(generatedAttrName, "true");
			}

			if(variable.isMakeExternal()) {
				variableElem.setAttribute(makeExternalAttrName, "true");
			}

			variablesElem.addContent(variableElem);
		}
	}

	//------------------------------------------------------------------------

	/**
	 * Replace variable with number.
	 *
	 * @param paramElem the param elem
	 */
	private void replaceVariableWithNumber(Element paramElem){
		String variable = paramElem.getTextTrim();

		if(strategy.variables().get(variable) != null) {
			Variable var = strategy.variables().get(variable);
			if (var != null) {
				if (var.isAutoGenerated()) { // bug https://roadmap.strategyquant.com/tasks/sq4_011225
					// we should convert vars to numbers only for autogenerated variables!
					paramElem.setText(strategy.variables().get(variable).getValue());
					paramElem.setAttribute("variable", "false");
				} else {
					Element elVariable = var.getXML();
					if(elVariable != null && XMLUtil.elementIs(elVariable, generatedAttrName)) {
						paramElem.setText(var.getValue());
						paramElem.setAttribute("variable", "false");
					}
				}
			} else {
				//Log.error("Cannot find variable '" + variable + "'");
			}
		}
	}

	//------------------------------------------------------------------------

	/**
	 * Removes the generated variables.
	 *
	 * @throws Exception the exception
	 */
	private void removeGeneratedVariables() throws Exception{
		Element variablesElem = getChildElem(getChildElem(strategy.getStrategyXml(), "Strategy"), "Variables");
		Iterator<Element> iterator = variablesElem.getChildren("variable").iterator();

		while(iterator.hasNext()) {
			Element variableElem = iterator.next();
			if(XMLUtil.elementIs(variableElem, generatedAttrName) && XMLUtil.elementIsNot(variableElem, makeExternalAttrName)){
				iterator.remove();
			}
		}

		Iterator<Variable> varIterator = strategy.variables().iterator();
		while(varIterator.hasNext()){
			Variable variable = varIterator.next();
			Element elVariable = variable.getXML();

			if(XMLUtil.elementIs(elVariable, generatedAttrName) && XMLUtil.elementIsNot(elVariable, makeExternalAttrName)){
				if(variable.isAutoGenerated()) {
					varIterator.remove();
				}
			}
		}

	}

	//------------------------------------------------------------------------

	/**
	 * Gets the child elem.
	 *
	 * @param parentElem the parent elem
	 * @param childName the child name
	 * @return the child elem
	 * @throws Exception the exception
	 */
	private Element getChildElem(Element parentElem, String childName) throws Exception{
		Element elChild = parentElem.getChild(childName);
		if(elChild == null) throw new Exception("Project config doesn't contain '" + childName + "' element");
		return elChild;
	}

	//------------------------------------------------------------------------

	/**
	 * Gets the rule type.
	 *
	 * @param ruleElem the rule elem
	 * @return the rule type
	 * @throws Exception the exception
	 */
	private RuleType getRuleType(Element ruleElem) throws Exception{
		String name = ruleElem.getAttributeValue("name");
		if(name == null){
			throw new Exception("Rule doesn't have a name");
		}

		if(name.startsWith("Long")) return RuleType.LONG;
		else if(name.startsWith("Short")) return RuleType.SHORT;
		else if(name.startsWith("Trading signals")) return RuleType.TRADING_SIGNALS;
		else if(name.startsWith("Explore")) return RuleType.EXPLORE;
		else return RuleType.UNKNOWN;
	}

	//------------------------------------------------------------------------

	/**
	 * Find items.
	 *
	 * @param ruleElem the rule elem
	 * @return the array list
	 */
	private ArrayList<Element> findItems(Element ruleElem){
		ArrayList<Element> items = new ArrayList<>();

		ArrayList<Element> nestedElems = XMLUtil.getNestedElements(ruleElem, "Item");

		for(int i=0; i<nestedElems.size(); i++){
			Element itemElem = nestedElems.get(i);

			if(itemValid(itemElem)){	//block items don't have identification attribute
				items.add(itemElem);
			}
		}

		return items;
	}

	//------------------------------------------------------------------------

	/**
	 * Item valid.
	 *
	 * @param itemElem the item elem
	 * @return true, if successful
	 */
	private boolean itemValid(Element itemElem){
		String key = itemElem.getAttributeValue("key");
		return key != null && !key.equals("AND") && !key.equals("OR");
	}

	//------------------------------------------------------------------------

	/**
	 * Gets the param key.
	 *
	 * @param paramElem the param elem
	 * @param itemKey the item key
	 * @return the param key
	 */
	private String getParamKey(Element paramElem, String itemKey){
		String paramKey = paramElem.getAttributeValue("key");
		String type = paramElem.getAttributeValue("type");

		if(paramKey == null) {
			Log.error("Parameter of item '" + itemKey + "' doesn't have key attribute");

		} else if(paramNotAllowed(paramKey, itemKey)){
			//Magic numbers ignored

		} else if(type == null){

			if(paramKey.equals("#Number#")) {
				return paramKey;
			}

			Log.error("Parameter '{}' doesn't have type attribute", paramKey);

		} else if(type.equals("unknown")){
			//unknown types ignored
		}
		else {
			return paramKey;
		}

		return null;
	}

	//------------------------------------------------------------------------

	/**
	 * Param not allowed.
	 *
	 * @param paramKey the param key
	 * @param itemKey the item key
	 * @return true, if successful
	 */
	private boolean paramNotAllowed(String paramKey, String itemKey){
		return paramKey.equals("#MagicNumber#") ||
				paramKey.equals("#ComputedFrom#") ||
				(itemKey.startsWith("EnterAt") && paramKey.equals("#Direction#")) ||
				(itemKey.startsWith("EnterAt") && paramKey.equals("#Size#"));
	}

	//------------------------------------------------------------------------

	/**
	 * Checks if is transformed.
	 *
	 * @return true, if is transformed
	 */
	private boolean isTransformed(){
		try {
			Element variablesElem = getChildElem(getChildElem(strategy.getStrategyXml(), "Strategy"), "Variables");
			if(variablesElem != null){
				for(Element variableElem : variablesElem.getChildren("variable")){
//					if(XMLUtil.elementIs(variableElem, generatedAttrName) && XMLUtil.elementIsNot(variableElem, makeExternalAttrName)){
					// bug from Alex - it didn't set parameters when they were defined externally in AW editor
					if(XMLUtil.elementIsNot(variableElem, makeExternalAttrName)){
						return true;
					}
				}
			}
		} catch (Exception e){
			Log.error("Error while checking transformed state. ", e);
		}
		return false;
	}

	//------------------------------------------------------------------------

	/**
	 * Checks if is symmetry enabled.
	 *
	 * @return true, if is symmetry enabled
	 */
	public boolean isSymmetryEnabled() {
		return symmetryEnabled;
	}

}
