package SQ.Internal;

import java.text.DecimalFormat;

import org.jdom2.Element;

import com.strategyquant.tradinglib.ParametrizationTypes;
import com.strategyquant.tradinglib.StrategyBase;
import com.strategyquant.tradinglib.Variable;
import com.strategyquant.tradinglib.Variables;
import com.strategyquant.tradinglib.indicator.IndicatorsObj;
import com.strategyquant.tradinglib.optimization.OptimizationSettings;
import com.strategyquant.tradinglib.optimization.Parameter;
import com.strategyquant.tradinglib.optimization.IStrategyModifier;
import com.strategyquant.tradinglib.optimization.StrategyParamData;

/**
 * The Class XmlStrategyModifier.
 */
public class XmlStrategyModifier implements IStrategyModifier {

	/**
	 * Creates the strategy variation.
	 *
	 * @param strategy the strategy
	 * @param optimizationSettings the optimization settings
	 * @param indexes the indexes
	 * @return the strategy param data
	 * @throws Exception the exception
	 */
	@Override
	public StrategyParamData createStrategyVariation(StrategyBase strategy, OptimizationSettings optimizationSettings, short[] indexes) throws Exception {
		if(!(strategy instanceof XmlStrategy)) {
			throw new Exception("Not implemeted yet!");
		}
		
		// create clone of strategy
		XmlStrategy xmlS = new XmlStrategy(strategy.getStrategyXml().clone(), strategy.getStrategyName());
		
		StringBuilder sb = new StringBuilder();
		
		//SQUtils.stringToFile(new File(MainApp.getDataPath()+"tests/tmp/AAA.txt"), XMLUtil.elementToString(strategy.getStrategyXml()));
		DecimalFormat df = new DecimalFormat("#.######");
		
		// now set parameters according to indexes
		for(int i=0; i<optimizationSettings.parameters.size(); i++) {
			Parameter param = optimizationSettings.parameters.get(i);
			
			int stepIndex = -1;
			
			if(param.isUsed()) {
				// set variable to value according to index
				//stepIndex = indexes[processedIndexes];
				stepIndex = indexes[i];
			}
				
			double value = param.getValueByIndex(stepIndex);

			if(xmlS.variables().canSetValue(param.getName())){
				xmlS.variables().setValue(param.getName(), value);
			}
			
			if(param.isUsed()) {
				String paramValue = df.format(value).replace(",", ".");
				if(param.getType() == Variable.TypeBoolean) {
					paramValue = paramValue.equals("1") ? "true" : "false";
				}
				
				sb.append(param.getName());
				sb.append("=");
				sb.append(paramValue);
				sb.append(",");
			}
		}

		//remove unused trading options variables
		
		for(int i=xmlS.variables().size() - 1; i>=0; i--) {
			Variable var = xmlS.variables().get(i);
			if(var.getParamType() == null || !var.getParamType().equals(ParametrizationTypes.ParamTypeTradingOptions)) continue;
			
			boolean remove = true;
			
			for(int a=0; a<optimizationSettings.parameters.size(); a++) {
				Parameter param = optimizationSettings.parameters.get(a);
				
				if(param.getName().equals(var.getName())) {
					remove = !param.isUsed();
					break;
				}
			}
			
			if(remove) {
				xmlS.variables().remove(i);
			}
		}
		
		regenerateVariablesXML(xmlS);
		//SQUtils.stringToFile(new File(MainApp.getDataPath()+"tests/tmp/AAA2.txt"), XMLUtil.elementToString(strategy.getStrategyXml()));
		
		return new StrategyParamData(xmlS, sb.toString());
	}

	//------------------------------------------------------------------------

	/**
	 * Regenerate variables XML.
	 *
	 * @param strategy the strategy
	 * @throws Exception the exception
	 */
	private void regenerateVariablesXML(XmlStrategy strategy) throws Exception{
		Element variablesElem = strategy.getStrategyXml().getChild("Strategy").getChild("Variables");
		
		variablesElem.removeContent();
		
		for(int i=0; i<strategy.variables().size(); i++) {
			Variable variable = strategy.variables().get(i);
		
			Element variableElem = variable.getXML().detach();

			if(variable.isAutoGenerated()){
				variableElem.setAttribute("autoGenerated", "true");
			}
			
			variablesElem.addContent(variableElem);
		}
	}

	/**
	 * Creates the strategy from xml.
	 *
	 * @param elStrategy the el strategy
	 * @param strategyName the strategy name
	 * @return the strategy base
	 * @throws Exception the exception
	 */
	@Override
	public StrategyBase createStrategyFromXml(Element elStrategy, String strategyName) throws Exception {
		return new XmlStrategy(elStrategy, strategyName);
	}

	/**
	 * Creates the indicators object.
	 *
	 * @return the indicators obj
	 */
	@Override
	public IndicatorsObj createIndicatorsObject(StrategyBase strategy) {
		return new Indicators(strategy);
	}

}
