package com.strategyquant.tradinglib.engine.stockpicker.backtester.log;

import com.strategyquant.lib.SQTime;
import com.strategyquant.lib.SQUtils;
import com.strategyquant.tradinglib.engine.stockpicker.PortfolioTrader;
import com.strategyquant.tradinglib.engine.stockpicker.signals.Signals;
import com.strategyquant.tradinglib.strategy.LiveOrderObj;
import it.unimi.dsi.fastutil.objects.ObjectArrayList;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class StockpickerLog {
   public static final Logger Log = LoggerFactory.getLogger(StockpickerLog.class);
   private StringBuilder b = new StringBuilder();
   public boolean storeLogs = false;
   private static final String BacktestDetails = "#BacktestDetails#";

   public void init(String var1, String var2, long var3, long var5) {
      if (this.storeLogs) {
         this.b.append("//--------------------------------------------------------------------\n");
         this.b.append(String.format("// Stockpicker backtest log of %s\n", var1));
         this.b.append("// \n");
         this.b.append("// Generated by StrategyQuant X\n");
         this.b.append("// \n");
         this.b.append(String.format("// Backtested on %s / D1, %s - %s\n", var2, SQTime.toDateString(var3), SQTime.toDateString(var5)));
         this.b.append("// \n");
         this.b.append("#BacktestDetails#\n");
         this.b.append("//--------------------------------------------------------------------\n");
      }
   }

   public void print(Signals var1, PortfolioTrader var2, boolean var3) {
      if (this.storeLogs) {
         if (var3) {
            if (var1 != null && var1.longEntrySignalExists()) {
               this.b.append("Entry signals Long (");
               this.b.append(var1.getLongEntrySignals().list().size());
               this.b.append("): ");
               var1.getLongEntrySignals().toString(this.b);
               this.b.append("\n");
            } else {
               this.b.append("Entry signals Long (0): \n");
            }

            if (var1 != null && var1.shortEntrySignalExists()) {
               this.b.append("Entry signals Short (");
               this.b.append(var1.getShortEntrySignals().list().size());
               this.b.append("): ");
               var1.getShortEntrySignals().toString(this.b);
               this.b.append("\n");
            } else {
               this.b.append("Entry signals Short (0): \n");
            }

            if (var1 != null && var1.exitSignalExists()) {
               this.b.append("Exit signals (");
               this.b.append(var1.getExitSignals().size());
               this.b.append("): ");
               var1.getExitSignals().toString(this.b);
               this.b.append("\n");
            } else {
               this.b.append("Exit signals (0): \n");
            }
         } else {
            this.b.append("\nPending orders (");
            this.b.append(var2.openPosCount(true));
            this.b.append("): ");
            var2.printOpenTrades(this.b, true);
            this.b.append("\n");
            this.b.append("Canceled orders (");
            this.b.append(var2.broker.statsCanceledOrders.size());
            this.b.append("): ");
            this.print(this.b, var2.broker.statsCanceledOrders);
            this.b.append("\n");
            this.b.append("Opened positions (");
            this.b.append(var2.broker.statsOpenedPositions.size());
            this.b.append("): ");
            this.print(this.b, var2.broker.statsOpenedPositions);
            this.b.append("\n");
            this.b.append("Closed positions (");
            this.b.append(var2.broker.statsClosedPositions.size());
            this.b.append(" / $");
            this.b.append(this.totalPL(var2.broker.statsClosedPositions));
            this.b.append("): ");
            this.print(this.b, var2.broker.statsClosedPositions);
            this.b.append("\n");
            this.b.append("\nOpen positions (");
            this.b.append(var2.openPosCount(false));
            this.b.append("): ");
            var2.printOpenTrades(this.b, false);
            this.b.append("\n");
            this.b.append("Account balance: $");
            this.b.append(SQUtils.d2(var2.getAccountBalance()));
            this.b.append(", equity: $");
            this.b.append(SQUtils.d2(var2.getAccountEquity()));
            this.b.append("\n");
         }
      }
   }

   private String totalPL(ObjectArrayList<LiveOrderObj> var1) {
      double var2 = 0.0;

      for (int var4 = 0; var4 < var1.size(); var4++) {
         LiveOrderObj var5 = (LiveOrderObj)var1.get(var4);
         var2 += var5.getPL();
      }

      return var2 == 0.0 ? "0" : SQUtils.d2(var2);
   }

   private void print(StringBuilder var1, ObjectArrayList<LiveOrderObj> var2) {
      for (int var3 = 0; var3 < var2.size(); var3++) {
         LiveOrderObj var4 = (LiveOrderObj)var2.get(var3);
         var1.append(var4.getSymbol());
         var1.append(", ");
      }
   }

   public void print(String var1) {
      if (this.storeLogs) {
         this.b.append(var1 + "\n");
      }
   }

   public String toString(String var1) {
      String var2 = this.b.toString();
      if (var2 != null) {
         var2 = var2.replace("#BacktestDetails#", var1);
      }

      return var2;
   }

   public void storeLogs(boolean var1) {
      this.storeLogs = var1;
   }

   public boolean storeLogs() {
      return this.storeLogs;
   }
}
