<#--########################################################################
  Warning! Do not delete this header, it is used by StrategyQuant to get
  information about this code generator.

  <name>Pseudo Code(*.TXT)</name>
  <extensionName>Pseudo Source Code (*.TXT)</extensionName>
  <extension>txt</extension>
  <parametersChoice>true</parametersChoice>
  <description>Saves strategy as human readable pseudo code,
  ready for manual trading</description>
#########################################################################-->
<@compress single_line=true>
<#include "/global/globalFunctions.inc">
<#include "/PseudoCode/Functions.inc">
<#include "/PseudoCode/pseudoBlocks.inc">
<#include "/PseudoCode/pseudoParameters.inc">
<#include "/PseudoCode/ATM.inc">
<#assign ExitMethodsList = ["StopLoss", "ProfitTarget", "MoveSL2BE", "TrailingStop", "ExitAfterBars"] />
</@compress>
//--------------------------------------------------------------------
// Pseudo Source Code of ${getOptions("StrategyName")}
//
//   Generated by StrategyQuant ${getOptions("Version")} for ${getOptions("Engine")}
//   at ${getOptions("Date")}
//
//   <@printBacktestInfo />
//   Backtest engine: ${getOptions("BacktestEngine")}
//--------------------------------------------------------------------
<#if doc.StrategyFile.Strategy.@pickerEditor[0]?? && doc.StrategyFile.Strategy.@pickerEditor[0] == "true">

  <#if doc.StrategyFile.Strategy.@singleAsset[0]?? && doc.StrategyFile.Strategy.@singleAsset[0] == "true">
Strategy type: AlgoCloud Single-asset 
  <#else>
Strategy type: AlgoCloud Stockpicker
  </#if>
Entry triggered at: ${doc.StrategyFile.Strategy.@entryTriggeredAt}
Exit triggered at: ${doc.StrategyFile.Strategy.@exitTriggeredAt}
</#if>

<#if hasVariables(true) >

//--------------------------------------------------------------------
//  Strategy Parameters
//--------------------------------------------------------------------
<@printVariables />
</#if>

<@printSubcharts />

//--------------------------------------------------------------------
// Trading options logic
//--------------------------------------------------------------------
<@printTradingOptions />


<#if getRulesCountForEvent("OnInit") gt 0 >
<@printRulesForEvent "OnInit" "Initialization:" />
</#if>
<#if getRulesCountForEvent("OnBarUpdate") gt 0 >
<@printRulesForEvent "OnBarUpdate" "Trading rule:" />

</#if>
<#if getRulesCountForEvent("OnDeinit") gt 0 >
<@printRulesForEvent "OnDeinit" "Deinitialization:" />
</#if>

Broker: <@printTradingOptionIntValue "BrokerOption" "PickerBroker" />
