package com.strategyquant.tradinglib;

import com.strategyquant.lib.L;
import com.strategyquant.lib.SQUtils;
import java.lang.reflect.Field;
import java.util.ArrayList;
import org.jdom2.Element;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class Variable {
   public static final Logger Log = LoggerFactory.getLogger("Variable");
   public static final byte TypeUnknown = 0;
   public static final byte TypeInt = 1;
   public static final byte TypeBoolean = 2;
   public static final byte TypeString = 3;
   public static final byte TypeDouble = 4;
   public static final byte TypeTime = 5;
   public static final byte TypeCustomParam = 6;
   public static final String DayTradeOn = "Day_Trade_On";
   private String id;
   private String type;
   private byte internalType;
   private String name;
   private String value;
   private String paramType;
   private ArrayList<Variable.AttachedField> attachedFields = null;
   private Element elVariable;
   private boolean autoGenerated = false;
   private boolean makeExternal = false;
   private double min = -2.1474836E9F;
   private double max = -2.1474836E9F;
   private double dblValue = Double.MAX_VALUE;

   public Variable(Element var1) {
      this.elVariable = var1;
      this.id = var1.getChild("id").getValue();
      this.type = var1.getChild("type").getValue();
      this.internalType = this.recognizeType();
      this.name = var1.getChild("name").getValue();
      this.value = var1.getChild("value").getValue();

      try {
         this.paramType = var1.getChild("paramType").getValue();
      } catch (Exception var5) {
      }

      try {
         this.makeExternal = Boolean.parseBoolean(var1.getChild("makeExternal").getValue());
      } catch (Exception var4) {
      }

      try {
         this.autoGenerated = Boolean.parseBoolean(var1.getAttributeValue("autoGenerated"));
      } catch (Exception var3) {
      }
   }

   public Variable(String var1, String var2, String var3, String var4, boolean var5, boolean var6) {
      this(var1, var2, var3, var4, var5, null, var6);
   }

   public Variable(String var1, String var2, String var3, String var4, boolean var5, String var6, boolean var7) {
      this.id = var1;
      this.name = var2;
      this.type = var3;
      this.internalType = this.recognizeType();
      this.value = var4;
      this.autoGenerated = var5;
      this.paramType = var6;
      this.makeExternal = var7;
   }

   public Variable(Object var1, Field var2) {
      this.id = var2.getName();
      this.name = this.id;
      this.type = var2.getType().getTypeName();
      this.internalType = this.recognizeType();

      try {
         this.value = var2.get(var1).toString();
      } catch (IllegalArgumentException var4) {
         var4.printStackTrace();
         Log.error("Cannot set variable value from field", var4);
      } catch (IllegalAccessException var5) {
         var5.printStackTrace();
         Log.error("Cannot set variable value from field", var5);
      }

      this.registerAttachedField(var1, var2);
   }

   private byte recognizeType() {
      switch (this.type) {
         case "int":
            return 1;
         case "bool":
         case "boolean":
            return 2;
         case "string":
            return 3;
         case "java.lang.String":
            return 3;
         case "double":
            return 4;
         case "time":
            return 5;
         case "customParam":
            return 6;
         default:
            return 0;
      }
   }

   public String getId() {
      return this.id;
   }

   public String getValue() {
      return this.dblValue != Double.MAX_VALUE ? SQUtils.doubleToString(this.dblValue) : this.value;
   }

   public String getName() {
      return this.name;
   }

   public String getType() {
      return this.type;
   }

   public byte getInternalType() {
      return this.internalType;
   }

   public int getValueAsInt() {
      if (this.value.equals("0.0")) {
         return 0;
      } else {
         return this.value.equals("1.0") ? 1 : Integer.parseInt(this.value);
      }
   }

   public double getValueAsDouble() {
      return Double.parseDouble(this.value);
   }

   public boolean getValueAsBoolean() {
      return Boolean.parseBoolean(this.value);
   }

   public void registerAttachedField(Object var1, Field var2) {
      if (this.attachedFields == null) {
         this.attachedFields = new ArrayList<>();
      }

      this.attachedFields.add(new Variable.AttachedField(var1, var2));
   }

   public void setValue(int var1) {
      this.checkAndSet((byte)1, var1);
   }

   public void setValue(double var1) {
      this.checkAndSetDouble(var1);
   }

   public void setValue(boolean var1) {
      this.checkAndSet((byte)2, var1);
   }

   public void setValue(String var1) {
      this.checkAndSet((byte)3, var1);
   }

   public void setValueInXml(double var1) {
      if (this.elVariable == null) {
         throw new IllegalArgumentException("Variable element is null, you cannot set it!");
      }

      String var3 = null;
      if (this.getInternalType() == 1 || this.getInternalType() == 5) {
         var3 = Integer.toString((int)var1);
      } else if (this.getInternalType() == 4) {
         var3 = Double.toString(var1);
         this.dblValue = var1;
      } else {
         if (this.getInternalType() != 2) {
            throw new IllegalArgumentException("You cannot set int value for variable of type " + this.type);
         }

         var3 = Boolean.toString(var1 != 0.0);
      }

      this.elVariable.getChild("value").setText(var3);
   }

   public void setFromString(String var1) throws Exception {
      try {
         switch (this.internalType) {
            case 1:
               this.checkAndSet((byte)1, Integer.parseInt(var1.split("\\.")[0]));
               break;
            case 2:
               this.checkAndSet((byte)2, Boolean.parseBoolean(var1));
               break;
            case 3:
               this.checkAndSet((byte)3, String.valueOf(var1));
               break;
            case 4:
               this.checkAndSet((byte)4, Double.parseDouble(var1));
               break;
            case 5:
               this.checkAndSet((byte)1, Integer.parseInt(var1));
               break;
            default:
               throw new Exception(L.t("Cannot set value from string to variable of unknown type", new Object[0]));
         }
      } catch (NumberFormatException var3) {
         throw new NumberFormatException("Cannot convert string '" + var1 + "' for variable '" + this.name + "'");
      }
   }

   private void checkAndSet(byte var1, Object var2) {
      String var3 = null;
      if (var1 == 1) {
         if (this.getInternalType() != 1 && this.getInternalType() != 4 && this.getInternalType() != 5) {
            throw new IllegalArgumentException("You cannot set int value for variable of type " + this.type);
         }

         var3 = Integer.toString((Integer)var2);
      } else if (var1 == 4) {
         if (this.getInternalType() != 1 && this.getInternalType() != 4) {
            throw new IllegalArgumentException("You cannot set double value for variable of type " + this.type);
         }

         var3 = Double.toString((Double)var2);
      } else if (var1 == 2) {
         if (this.getInternalType() != 2) {
            throw new IllegalArgumentException("You cannot set boolean value for variable of type " + this.type);
         }

         var3 = Boolean.toString((Boolean)var2);
      } else if (var1 == 3) {
         if (this.getInternalType() != 3) {
            throw new IllegalArgumentException("You cannot set String value for variable of type " + this.type);
         }

         var3 = (String)var2;
      }

      if (this.value == null || !this.value.equals(var3)) {
         this.value = var3;
         if (this.attachedFields != null) {
            for (int var4 = 0; var4 < this.attachedFields.size(); var4++) {
               Variable.AttachedField var5 = this.attachedFields.get(var4);
               String var6 = var5.fieldClass;
               if (var6.equals("int")) {
                  this.setField(var5, this.getIntValue(var2));
               } else if (var6.equals("double")) {
                  this.setField(var5, this.getDoubleValue(var2));
               } else if (var6.equals("boolean")) {
                  this.setField(var5, this.getBooleanValue(var2));
               } else {
                  this.setField(var5, var2);
               }
            }
         }

         if (this.elVariable != null) {
         }
      }
   }

   private void checkAndSetDouble(double var1) {
      if (this.getInternalType() != 1 && this.getInternalType() != 4) {
         throw new IllegalArgumentException("You cannot set double value for variable of type " + this.type);
      }

      if (this.dblValue == Double.MAX_VALUE || this.dblValue != var1) {
         this.dblValue = var1;
         if (this.attachedFields != null) {
            for (int var3 = 0; var3 < this.attachedFields.size(); var3++) {
               Variable.AttachedField var4 = this.attachedFields.get(var3);
               String var5 = var4.fieldClass;
               if (var5.equals("int")) {
                  this.setField(var4, this.getIntValue(var1));
               } else if (var5.equals("double")) {
                  this.setFieldDouble(var4, this.dblValue);
               } else if (var5.equals("boolean")) {
                  this.setField(var4, this.getBooleanValue(var1));
               } else {
                  this.setField(var4, var1);
               }
            }
         }
      }
   }

   private boolean getBooleanValue(Object var1) {
      if (var1 instanceof Boolean) {
         return (Boolean)var1;
      } else if (var1 instanceof Integer) {
         return (Integer)var1 != 0;
      } else if (var1 instanceof Double) {
         return (Double)var1 != 0.0;
      } else if (var1 instanceof Long) {
         return (Long)var1 != 0L;
      } else if (var1 instanceof String) {
         return Boolean.parseBoolean((String)var1);
      } else {
         throw new IllegalArgumentException("Unknown value type, cannot convert to boolean! " + var1);
      }
   }

   private double getDoubleValue(Object var1) {
      if (var1 instanceof Double) {
         return (Double)var1;
      } else if (var1 instanceof Integer) {
         return ((Integer)var1).doubleValue();
      } else if (var1 instanceof Long) {
         return ((Long)var1).doubleValue();
      } else if (var1 instanceof String) {
         return Double.parseDouble((String)var1);
      } else {
         throw new IllegalArgumentException("Unknown value type, cannot convert to double! " + var1);
      }
   }

   private int getIntValue(Object var1) {
      if (var1 instanceof Integer) {
         return (Integer)var1;
      } else if (var1 instanceof Double) {
         return ((Double)var1).intValue();
      } else if (var1 instanceof Long) {
         return ((Long)var1).intValue();
      } else if (var1 instanceof String) {
         return Integer.parseInt((String)var1);
      } else {
         throw new IllegalArgumentException("Unknown value type, cannot convert to int! " + var1);
      }
   }

   private void setField(Variable.AttachedField var1, Object var2) {
      try {
         var1.field.set(var1.object, var2);
      } catch (IllegalArgumentException var4) {
         Log.error("Error setting field for variable", var4);
      } catch (IllegalAccessException var5) {
         Log.error("Error setting field for variable", var5);
      }
   }

   private void setFieldDouble(Variable.AttachedField var1, double var2) {
      try {
         var1.field.setDouble(var1.object, var2);
      } catch (IllegalArgumentException var5) {
         Log.error("Error setting field for variable", var5);
      } catch (IllegalAccessException var6) {
         Log.error("Error setting field for variable", var6);
      }
   }

   public boolean isObjectRegistered(Object var1, String var2) {
      if (this.attachedFields == null) {
         return false;
      }

      for (Variable.AttachedField var4 : this.attachedFields) {
         if (var4.object == var1 && var4.field.getName().equals(var2)) {
            return true;
         }
      }

      return false;
   }

   public String translateType(byte var1) {
      switch (var1) {
         case 1:
            return "INT";
         case 2:
            return "BOOLEAN";
         case 3:
            return "STRING";
         case 4:
            return "DOUBLE";
         case 5:
            return "TIME";
         case 6:
            return "CustomParam";
         default:
            return "UNKNOWN";
      }
   }

   public Element getXML() {
      if (this.elVariable == null) {
         this.elVariable = new Element("variable");
      }

      this.elVariable.removeContent();
      this.elVariable.addContent(new Element("id").setText(this.id));
      this.elVariable.addContent(new Element("name").setText(this.name));
      this.elVariable.addContent(new Element("type").setText(this.type));
      if (this.dblValue != Double.MAX_VALUE) {
         this.elVariable.addContent(new Element("value").setText(SQUtils.doubleToString(this.dblValue)));
      } else {
         this.elVariable.addContent(new Element("value").setText(this.value));
      }

      this.elVariable.addContent(new Element("paramType").setText(this.paramType));
      boolean var1 = this.isAutoGenerated() || this.name != null && this.name.startsWith("Magic") || this.makeExternal;
      this.elVariable.addContent(new Element("makeExternal").setText(var1 ? "true" : "false"));
      return this.elVariable;
   }

   public boolean isAutoGenerated() {
      return this.autoGenerated;
   }

   public String getParamType() {
      return this.paramType;
   }

   public void setParamType(String var1) {
      this.paramType = var1;
   }

   public void setMinMax(double var1, double var3) {
      this.min = var1;
      this.max = var3;
   }

   public double getMin() {
      return this.min;
   }

   public double getMax() {
      return this.max;
   }

   public boolean isMakeExternal() {
      return this.makeExternal;
   }

   public void setMakeExternal(boolean var1) {
      this.makeExternal = var1;
   }

   @Override
   public String toString() {
      StringBuilder var1 = new StringBuilder(this.name);
      var1.append("=");
      var1.append(this.value);
      return var1.toString();
   }

   public Variable getClone() {
      Variable var1 = new Variable(this.id, this.name, this.type, this.value, this.autoGenerated, this.paramType, this.makeExternal);
      var1.internalType = this.internalType;
      var1.paramType = this.paramType;
      var1.min = this.min;
      var1.max = this.max;
      var1.elVariable = this.elVariable != null ? this.elVariable.clone() : null;
      var1.dblValue = this.dblValue;
      return var1;
   }

   class AttachedField {
      Object object;
      Field field;
      String fieldClass;

      public AttachedField(Object nullx, Field nullxx) {
         this.object = nullx;
         this.field = nullxx;
         this.fieldClass = nullxx.getType().getSimpleName();
      }
   }
}
