package com.strategyquant.plugin.Portfolio.impl.Composer;

import com.strategyquant.lib.SQTime;
import com.strategyquant.tradinglib.ResultsGroup;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class PortfolioComposerLog {
   public static final Logger Log = LoggerFactory.getLogger(PortfolioComposerLog.class);
   private StringBuilder b = new StringBuilder();

   public PortfolioComposerLog(String var1, PortfolioComposerSettings var2) {
      this.b.append("//--------------------------------------------------------------------\n");
      this.b.append(String.format("// PortfolioComposer log, portfolio %s\n", var1));
      this.b.append("// \n");
      this.b.append("// Generated by StrategyQuant X\n");
      this.b.append("// \n");
      this.b.append(String.format("// Strategies Weights : %s\n", this.getStrategies(var2)));
      this.b.append(String.format("// Start day: %s, End day: %s\n", SQTime.toDateString(var2.startDay), SQTime.toDateString(var2.endDay)));
      this.b.append(String.format("// Initial capital: %s, Leverage 1:%s\n", var2.initialCapital, var2.leverage));
      this.b.append("//--------------------------------------------------------------------\n");
   }

   private String getStrategies(PortfolioComposerSettings var1) {
      String var2 = "";

      for (int var6 = 0; var6 < var1.strategies.size(); var6++) {
         ResultsGroup var3 = var1.strategies.get(var6);
         double var4 = var1.weights.get(var6);
         var2 = var2 + var3.getName() + "/" + var4;
         if (var6 < var1.strategies.size() - 1) {
            var2 = var2 + ",";
         }
      }

      return var2;
   }

   public void print(String var1) {
      this.b.append(var1 + "\n");
   }

   public void printNoNewLine(String var1) {
      this.b.append(var1);
   }

   @Override
   public String toString() {
      return this.b.toString();
   }
}
