<#--########################################################################
  Warning! Do not delete this header, it is used by StrategyQuant to get
  information about this code generator.

  <name>EasyLanguage for Tradestation / MultiCharts (*.el)</name>
  <extensionName>EasyLanguage Code (*.el)</extensionName>
  <extension>el</extension>
  <parametersChoice>true</parametersChoice>
  <description>Saves strategy as EasyLanguage code</description>
#########################################################################-->
<@compress single_line=true>
<#include "/global/globalFunctions.inc">
<#include "/EasyLanguage/Functions.inc">
<#include "/EasyLanguage/Blocks.inc">
<#include "/EasyLanguage/Parameters.inc">
<#include "/EasyLanguage/TradingOptions.inc">
<#include "/EasyLanguage/MoneyManagement.inc">
<#include "/EasyLanguage/Size.inc">
<#include "/EasyLanguage/ATM.inc">
<#assign ExitMethodsList = ["MoveSL2BE", "TrailingStop", "ExitAfterBars"] />
</@compress>
//------------------------------------------------------------------
// EasyLanguage Code for Tradestation / MultiCharts of ${getOptions("StrategyName")}
//
//   Generated by StrategyQuant ${getOptions("Version")}
//   at ${getOptions("Date")}
//  
//   <@printBacktestInfo /> 
//
<@printSubcharts />
//------------------------------------------------------------------
[IntrabarOrderGeneration = false]

<@elPrintInputs />

<@elPrintVars />

<#if getRulesCountForEvent("OnInit") gt 0 >
// =================================================================
// Initialization Rules
// =================================================================
If not InitDone Then begin
	InitDone = true;
  <@printRulesForEvent "OnInit" />	
end;
</#if>

// =================================================================
// TRADING OPTIONS LOGIC
// =================================================================
OpenOrdersAllowed = true;
<@printTradingOptionsCodes />

// =================================================================
// TRADING RULES LOGIC
// =================================================================
               
<#if getRulesCountForEvent("OnBarUpdate") gt 0 >
<@printRulesForEvent "OnBarUpdate" />
</#if>



